//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, UIButton, UILabel, UIScrollView, UIView, UIWebView;

@interface AboutViewController : UIViewController <UIWebViewDelegate>
{
    UIScrollView *_scroll;
    UIWebView *_content;
    UIView *_topView;
    UIView *_bottomView;
    UIButton *_buttonContact;
    UIButton *_buttonTerms;
    UILabel *_imei;
}

@property(nonatomic) __weak UILabel *imei; // @synthesize imei=_imei;
@property(nonatomic) __weak UIButton *buttonTerms; // @synthesize buttonTerms=_buttonTerms;
@property(nonatomic) __weak UIButton *buttonContact; // @synthesize buttonContact=_buttonContact;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UIView *topView; // @synthesize topView=_topView;
@property(nonatomic) __weak UIWebView *content; // @synthesize content=_content;
@property(nonatomic) __weak UIScrollView *scroll; // @synthesize scroll=_scroll;
- (void).cxx_destruct;
- (void)clickedShare:(id)arg1;
- (void)clickedTerms:(id)arg1;
- (void)clickedContact:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)refresh;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

