//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APMDataTypeValidator : NSObject
{
}

+ (BOOL)isValidCurrencyCode:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidNumericValue:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidConditionalUserPropertyValue:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidConditionalUserPropertyName:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidConditionalUserPropertyOrigin:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidScreenParameterValue:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidInternalUserAttributeValue:(id)arg1 name:(id)arg2 failureCode:(int *)arg3;
+ (BOOL)isValidInternalUserAttributeName:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidPublicUserAttributeValue:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidPublicUserAttributeName:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidInternalEventParameterValue:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidInternalEventParameterName:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidInternalEventName:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidForwardedEventOrigin:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidInternalEventOrigin:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidPublicEventParameterValue:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidPublicEventParameterName:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidPublicEventName:(id)arg1 failureCode:(int *)arg2;
+ (BOOL)isValidValue:(id)arg1 minLength:(int)arg2 maxLength:(int)arg3 type:(int)arg4 failureCode:(int *)arg5;
+ (BOOL)isValidPublicName:(id)arg1 maxLength:(int)arg2 type:(int)arg3 failureCode:(int *)arg4;
+ (BOOL)isValidInternalName:(id)arg1 maxLength:(int)arg2 type:(int)arg3 failureCode:(int *)arg4;
+ (BOOL)isValidString:(id)arg1 minLength:(int)arg2 maxLength:(int)arg3 type:(int)arg4 failureCode:(int *)arg5;
+ (BOOL)hasReservedPrefixes:(id)arg1;
+ (void)initialize;

@end

