//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class APMPBEvent, NSDictionary, NSMutableDictionary, NSString;

@interface APMEvent : NSObject <NSCopying>
{
    NSMutableDictionary *_parameters;
    NSString *_origin;
    NSString *_name;
    double _timestamp;
    double _previousTimestamp;
}

+ (BOOL)isValidParameterKey:(id)arg1 isPublicEvent:(BOOL)arg2 errorParameters:(id)arg3;
+ (id)normalizedParametersForParameters:(id)arg1 isPublicEvent:(BOOL)arg2;
@property(readonly, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(readonly, nonatomic) double previousTimestamp; // @synthesize previousTimestamp=_previousTimestamp;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *origin; // @synthesize origin=_origin;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) APMPBEvent *protoEvent;
- (BOOL)addScreenParameters:(id)arg1;
@property(nonatomic, getter=isDebug) BOOL debug;
@property(nonatomic, getter=isRealtime) BOOL realtime;
@property(nonatomic, getter=isConversion) BOOL conversion;
- (id)copyWithParameters:(id)arg1;
- (id)copyWithPreviousTimestamp:(double)arg1;
- (id)initWithOrigin:(id)arg1 isPublic:(BOOL)arg2 name:(id)arg3 timestamp:(double)arg4 previousTimestamp:(double)arg5 parameters:(id)arg6;
- (id)initWithEventProto:(id)arg1;

@end

