//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class Offer, UIButton, UIView;

@interface CampaignViewController : UIViewController
{
    UIView *v;
    Offer *_offer;
    UIView *_blurView;
    UIView *_contentView;
    UIButton *_buttonOk;
    UIButton *_buttonBack;
}

@property(nonatomic) __weak UIButton *buttonBack; // @synthesize buttonBack=_buttonBack;
@property(nonatomic) __weak UIButton *buttonOk; // @synthesize buttonOk=_buttonOk;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *blurView; // @synthesize blurView=_blurView;
@property(retain, nonatomic) Offer *offer; // @synthesize offer=_offer;
- (void).cxx_destruct;
- (void)close;
- (void)clickedOk:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)showWithImage:(id)arg1 inView:(id)arg2;
- (void)viewDidLoad;

@end

