//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class Code, Offer, UIButton, UIImageView, UILabel, UITextView, UIView;

@interface CodeViewController : UIViewController
{
    BOOL _isQRcode;
    Code *_code;
    Offer *_offer;
    UIView *_blurView;
    UIView *_contentView;
    UILabel *_valid;
    UILabel *_codeLabel;
    UITextView *_text;
    UIButton *_buttonOk;
    UIView *_codeView;
    UIImageView *_qrCodeView;
}

@property BOOL isQRcode; // @synthesize isQRcode=_isQRcode;
@property(nonatomic) __weak UIImageView *qrCodeView; // @synthesize qrCodeView=_qrCodeView;
@property(nonatomic) __weak UIView *codeView; // @synthesize codeView=_codeView;
@property(nonatomic) __weak UIButton *buttonOk; // @synthesize buttonOk=_buttonOk;
@property(nonatomic) __weak UITextView *text; // @synthesize text=_text;
@property(nonatomic) __weak UILabel *codeLabel; // @synthesize codeLabel=_codeLabel;
@property(nonatomic) __weak UILabel *valid; // @synthesize valid=_valid;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *blurView; // @synthesize blurView=_blurView;
@property(retain, nonatomic) Offer *offer; // @synthesize offer=_offer;
@property(retain, nonatomic) Code *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (void)clickedCopy;
- (void)clickedBack:(id)arg1;
- (void)showWithImage:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setupCode;
- (void)viewDidLoad;

@end

