//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface Code : NSObject
{
    BOOL _consumed;
    NSString *_Id;
    NSString *_offerId;
    NSString *_code;
    NSMutableArray *_messages;
    double _validTo;
    double _created;
}

@property(nonatomic) BOOL consumed; // @synthesize consumed=_consumed;
@property(retain, nonatomic) NSMutableArray *messages; // @synthesize messages=_messages;
@property(nonatomic) double created; // @synthesize created=_created;
@property(nonatomic) double validTo; // @synthesize validTo=_validTo;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(retain, nonatomic) NSString *offerId; // @synthesize offerId=_offerId;
@property(retain, nonatomic) NSString *Id; // @synthesize Id=_Id;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

