//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface DrivingScoreCell : UITableViewCell
{
    UILabel *_score;
    UILabel *_city;
    UILabel *_street;
    UILabel *_duration;
}

@property(nonatomic) __weak UILabel *duration; // @synthesize duration=_duration;
@property(nonatomic) __weak UILabel *street; // @synthesize street=_street;
@property(nonatomic) __weak UILabel *city; // @synthesize city=_city;
@property(nonatomic) __weak UILabel *score; // @synthesize score=_score;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

