//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CustomActivityIndicator, NSArray, NSObject<OS_dispatch_group>, NSString, UIColor, UIImageView, UILabel, UIPickerView, UITableView, UITextField, UIToolbar, UIView;

@interface DrivingLogHistoryController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIPickerViewDelegate, UIPickerViewDataSource>
{
    CustomActivityIndicator *loading;
    UIPickerView *months;
    UIToolbar *toolBar;
    NSArray *drivingHistory;
    NSArray *monthsArray;
    NSObject<OS_dispatch_group> *serviceGroup;
    int wholeRidesCount;
    float wholeKmsCount;
    float wholeScore;
    UIColor *teal;
    UIColor *yellow;
    UIColor *red;
    NSArray *_availableMonths;
    float _wholeScoreValue;
    float _scoreValue;
    int _ridesValue;
    float _kmsValue;
    UIView *_monthPickerShadow;
    UIView *_monthPickerCorner;
    UITextField *_monthPicker;
    UIView *_score;
    UILabel *_scoreLabel;
    UILabel *_ridesKms;
    UITableView *_tableView;
    UIImageView *_historyIcon;
}

@property(nonatomic) __weak UIImageView *historyIcon; // @synthesize historyIcon=_historyIcon;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UILabel *ridesKms; // @synthesize ridesKms=_ridesKms;
@property(nonatomic) __weak UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(nonatomic) __weak UIView *score; // @synthesize score=_score;
@property(nonatomic) __weak UITextField *monthPicker; // @synthesize monthPicker=_monthPicker;
@property(nonatomic) __weak UIView *monthPickerCorner; // @synthesize monthPickerCorner=_monthPickerCorner;
@property(nonatomic) __weak UIView *monthPickerShadow; // @synthesize monthPickerShadow=_monthPickerShadow;
@property(nonatomic) float kmsValue; // @synthesize kmsValue=_kmsValue;
@property(nonatomic) int ridesValue; // @synthesize ridesValue=_ridesValue;
@property(nonatomic) float scoreValue; // @synthesize scoreValue=_scoreValue;
@property(nonatomic) float wholeScoreValue; // @synthesize wholeScoreValue=_wholeScoreValue;
@property(retain) NSArray *availableMonths; // @synthesize availableMonths=_availableMonths;
- (void).cxx_destruct;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (id)pickerView:(id)arg1 titleForRow:(int)arg2 forComponent:(int)arg3;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)hide;
- (void)show;
- (void)changeDateFromLabel:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)getWholeHistory;
- (BOOL)getSerializedHistoryForMonth:(id)arg1 month:(id)arg2 refresh:(BOOL)arg3;
- (void)serializeHistory:(id)arg1 month:(id)arg2;
- (void)getUserData:(id)arg1 month:(id)arg2 refresh:(BOOL)arg3;
- (void)checkIfNoData;
- (void)setTableViewDotLines;
- (void)setupPicker;
- (void)setupLabels;
- (id)findLayer:(id)arg1;
- (void)refresh;
- (id)getRightColor:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

