//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CustomActivityIndicator, LoginPopupViewController, NSDictionary, NSMutableDictionary, SYDriversBehaviorTrip, SYSearchResult, UIButton, UIImageView, UILabel, UIStackView, UIView;

@interface DriversBehaviourLogViewController : UIViewController
{
    LoginPopupViewController *lpvc;
    CustomActivityIndicator *loading;
    float score;
    NSMutableDictionary *params;
    BOOL noInternet;
    BOOL _withoutRouting;
    SYDriversBehaviorTrip *_trip;
    SYSearchResult *_searchResult;
    NSDictionary *_searchResultHistory;
    UIButton *_backButton;
    UILabel *_scoreLabel;
    UILabel *_resultLabel;
    UIStackView *_stackView;
    UILabel *_avgSpeed;
    UILabel *_maxSpeed;
    UILabel *_tripLength;
    UIView *_okButtonView;
    UIImageView *_warningIcon1;
    UIImageView *_warningIcon2;
    UILabel *_warningLabel1;
    UILabel *_warningLabel2;
    UIView *_scoreShadowView;
    UIView *_scoreBackgroundView;
}

@property(nonatomic) __weak UIView *scoreBackgroundView; // @synthesize scoreBackgroundView=_scoreBackgroundView;
@property(nonatomic) __weak UIView *scoreShadowView; // @synthesize scoreShadowView=_scoreShadowView;
@property(nonatomic) __weak UILabel *warningLabel2; // @synthesize warningLabel2=_warningLabel2;
@property(nonatomic) __weak UILabel *warningLabel1; // @synthesize warningLabel1=_warningLabel1;
@property(nonatomic) __weak UIImageView *warningIcon2; // @synthesize warningIcon2=_warningIcon2;
@property(nonatomic) __weak UIImageView *warningIcon1; // @synthesize warningIcon1=_warningIcon1;
@property(nonatomic) __weak UIView *okButtonView; // @synthesize okButtonView=_okButtonView;
@property(nonatomic) __weak UILabel *tripLength; // @synthesize tripLength=_tripLength;
@property(nonatomic) __weak UILabel *maxSpeed; // @synthesize maxSpeed=_maxSpeed;
@property(nonatomic) __weak UILabel *avgSpeed; // @synthesize avgSpeed=_avgSpeed;
@property(nonatomic) __weak UIStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) __weak UILabel *resultLabel; // @synthesize resultLabel=_resultLabel;
@property(nonatomic) __weak UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) NSDictionary *searchResultHistory; // @synthesize searchResultHistory=_searchResultHistory;
@property(retain, nonatomic) SYSearchResult *searchResult; // @synthesize searchResult=_searchResult;
@property(retain, nonatomic) SYDriversBehaviorTrip *trip; // @synthesize trip=_trip;
@property(nonatomic) BOOL withoutRouting; // @synthesize withoutRouting=_withoutRouting;
- (void).cxx_destruct;
- (void)hide;
- (void)show;
- (void)clickedBack:(id)arg1;
- (void)postUserData;
- (void)setupStackView;
- (void)setupLabelsAfterBackend;
- (void)setupLabels;
- (void)setupButtons;
- (void)refresh;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

