//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBSDKMarketingLogger : NSObject
{
}

+ (void)printDebugMessage:(id)arg1;
+ (id)findAbove:(id)arg1;
+ (void)logEvent:(unsigned int)arg1 paramters:(id)arg2;
+ (void)logEvent:(unsigned int)arg1 parameters:(id)arg2;
+ (void)logEvent:(unsigned int)arg1;

@end

