//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBSDKButtonIndexer : NSObject
{
}

+ (id)pathOf:(id)arg1;
+ (void)uploadButton:(id)arg1;
+ (id)hash:(id)arg1;
+ (void)appendButton:(id)arg1 fromClick:(BOOL)arg2;
+ (void)buttonClicked:(id)arg1;
+ (void)setupButtonIndexing;
+ (void)checkButtonIndexing;
+ (void)load;

@end

