//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FIRClearcutLoggerDelegate.h"

@class NSString;

@interface FIRDiagnostics : NSObject <FIRClearcutLoggerDelegate>
{
}

+ (id)diagnosticsUserDefault;
+ (BOOL)isDate:(id)arg1 inSameDayOrBeforeThan:(id)arg2;
+ (void)logHeartbeatWithLogger:(id)arg1 forApp:(id)arg2;
+ (void)logHeartbeatIfNeededWithLogger:(id)arg1 forApp:(id)arg2 userDefaults:(id)arg3;
+ (void)clearcutLoggerWillSendLogs:(id)arg1;
+ (void)logDiagnostics:(id)arg1 usingLogger:(id)arg2;
+ (void)logDiagnostics:(id)arg1;
+ (BOOL)writeString:(id)arg1 toURL:(id)arg2;
+ (id)stringAtURL:(id)arg1;
+ (id)filePathURLWithName:(id)arg1;
+ (id)installString;
+ (id)deviceModel;
+ (id)mapFromServiceStringToTypeEnum:(id)arg1;
+ (void)populateLogProtoWithInfoPlistValues:(id)arg1;
+ (void)populateLogProtoWithNumberOfLinkedFrameworks:(id)arg1;
+ (void)populateLogProtoWithInstalledServices:(id)arg1;
+ (void)populateLogProtoWithCommonInfo:(id)arg1 app:(id)arg2;
+ (void)sendLogsToClearcut:(id)arg1 usingLogger:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
+ (void)load;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

