//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class FIRInstanceIDCheckinPreferences, FIRInstanceIDKeyPair, NSDictionary, NSMutableArray, NSString, NSURLSessionDataTask;

@interface FIRInstanceIDTokenOperation : NSOperation
{
    BOOL _isFinished;
    BOOL _isExecuting;
    int _action;
    NSString *_authorizedEntity;
    NSString *_scope;
    NSDictionary *_options;
    FIRInstanceIDCheckinPreferences *_checkinPreferences;
    FIRInstanceIDKeyPair *_keyPair;
    int _result;
    NSURLSessionDataTask *_dataTask;
    NSMutableArray *_completionHandlers;
    CDUnknownBlockType _testBlock;
}

+ (id)HTTPAuthHeaderFromCheckin:(id)arg1;
+ (id)standardQueryItemsWithDeviceID:(id)arg1 scope:(id)arg2;
+ (id)requestWithAuthHeader:(id)arg1;
+ (id)sharedURLSession;
@property(copy, nonatomic) CDUnknownBlockType testBlock; // @synthesize testBlock=_testBlock;
@property(readonly) NSMutableArray *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
@property(retain) NSURLSessionDataTask *dataTask; // @synthesize dataTask=_dataTask;
@property(readonly, nonatomic) int result; // @synthesize result=_result;
@property(retain, nonatomic) FIRInstanceIDKeyPair *keyPair; // @synthesize keyPair=_keyPair;
@property(retain, nonatomic) FIRInstanceIDCheckinPreferences *checkinPreferences; // @synthesize checkinPreferences=_checkinPreferences;
@property(readonly, nonatomic) NSDictionary *options; // @synthesize options=_options;
@property(readonly, nonatomic) NSString *scope; // @synthesize scope=_scope;
@property(readonly, nonatomic) NSString *authorizedEntity; // @synthesize authorizedEntity=_authorizedEntity;
@property(readonly, nonatomic) int action; // @synthesize action=_action;
- (void).cxx_destruct;
- (id)queryItemsWithKeyPair:(id)arg1;
- (void)performTokenOperation;
- (void)cancel;
- (void)finishWithResult:(int)arg1 token:(id)arg2 error:(id)arg3;
- (void)start;
- (void)setFinished:(BOOL)arg1;
- (BOOL)isFinished;
- (void)setExecuting:(BOOL)arg1;
- (BOOL)isExecuting;
- (BOOL)isAsynchronous;
- (void)addCompletionHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithAction:(int)arg1 forAuthorizedEntity:(id)arg2 scope:(id)arg3 options:(id)arg4 checkinPreferences:(id)arg5 keyPair:(id)arg6;

@end

