//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface FIRInstanceIDBackupExcludedPlist : NSObject
{
    BOOL _fileInStandardDirectory;
    NSDictionary *_cachedPlistContents;
    NSString *_fileName;
    NSString *_subDirectoryName;
}

@property(nonatomic) BOOL fileInStandardDirectory; // @synthesize fileInStandardDirectory=_fileInStandardDirectory;
@property(copy, nonatomic) NSString *subDirectoryName; // @synthesize subDirectoryName=_subDirectoryName;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSDictionary *cachedPlistContents; // @synthesize cachedPlistContents=_cachedPlistContents;
- (void).cxx_destruct;
- (unsigned int)supportedDirectory;
- (BOOL)doesFileExistInDirectory:(unsigned int)arg1;
- (id)pathWithName:(id)arg1 inDirectory:(unsigned int)arg2;
- (id)plistPathInDirectory:(unsigned int)arg1;
- (unsigned int)plistDirectory;
- (BOOL)doesFileExist;
- (BOOL)moveToApplicationSupportSubDirectory:(id)arg1;
- (id)contentAsDictionary;
- (BOOL)deleteFile:(id *)arg1;
- (BOOL)writeDictionary:(id)arg1 error:(id *)arg2;
- (id)initWithFileName:(id)arg1 subDirectory:(id)arg2;

@end

