//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class FIRMessagingCheckinService, NSDictionary, NSString, NSURLSessionDataTask;

@interface FIRMessagingTopicOperation : NSOperation
{
    BOOL _isFinished;
    BOOL _isExecuting;
    NSString *_topic;
    int _action;
    NSString *_token;
    NSDictionary *_options;
    FIRMessagingCheckinService *_checkinService;
    CDUnknownBlockType _completion;
    NSURLSessionDataTask *_dataTask;
}

+ (id)sharedSession;
@property(retain) NSURLSessionDataTask *dataTask; // @synthesize dataTask=_dataTask;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) FIRMessagingCheckinService *checkinService; // @synthesize checkinService=_checkinService;
@property(copy, nonatomic) NSDictionary *options; // @synthesize options=_options;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(nonatomic) int action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *topic; // @synthesize topic=_topic;
- (void).cxx_destruct;
- (void)performSubscriptionChange;
- (void)cancel;
- (void)finishWithError:(id)arg1;
- (void)start;
- (void)setFinished:(BOOL)arg1;
- (BOOL)isFinished;
- (void)setExecuting:(BOOL)arg1;
- (BOOL)isExecuting;
- (BOOL)isAsynchronous;
- (void)dealloc;
- (id)initWithTopic:(id)arg1 action:(int)arg2 token:(id)arg3 options:(id)arg4 checkinService:(id)arg5 completion:(CDUnknownBlockType)arg6;

@end

