//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FIRMessagingConnectionDelegate.h"

@class FIRMessagingConnection, FIRMessagingDataMessageManager, FIRMessagingRegistrar, FIRMessagingRmqManager, GULReachabilityChecker, NSString;

@interface FIRMessagingClient : NSObject <FIRMessagingConnectionDelegate>
{
    BOOL _stayConnected;
    BOOL _didScheduleReconnect;
    FIRMessagingConnection *_connection;
    FIRMessagingDataMessageManager *_dataMessageManager;
    id <FIRMessagingClientDelegate> _clientDelegate;
    FIRMessagingRegistrar *_registrar;
    NSString *_senderId;
    FIRMessagingRmqManager *_rmq2Manager;
    GULReachabilityChecker *_reachability;
    unsigned int _connectRetryCount;
    CDUnknownBlockType _connectHandler;
    long long _lastConnectedTimestamp;
    long long _lastDisconnectedTimestamp;
    double _connectionTimeoutInterval;
}

@property(copy, nonatomic) CDUnknownBlockType connectHandler; // @synthesize connectHandler=_connectHandler;
@property(nonatomic) BOOL didScheduleReconnect; // @synthesize didScheduleReconnect=_didScheduleReconnect;
@property(nonatomic) double connectionTimeoutInterval; // @synthesize connectionTimeoutInterval=_connectionTimeoutInterval;
@property(nonatomic) BOOL stayConnected; // @synthesize stayConnected=_stayConnected;
@property(nonatomic) unsigned int connectRetryCount; // @synthesize connectRetryCount=_connectRetryCount;
@property(nonatomic) long long lastDisconnectedTimestamp; // @synthesize lastDisconnectedTimestamp=_lastDisconnectedTimestamp;
@property(nonatomic) long long lastConnectedTimestamp; // @synthesize lastConnectedTimestamp=_lastConnectedTimestamp;
@property(nonatomic) __weak GULReachabilityChecker *reachability; // @synthesize reachability=_reachability;
@property(nonatomic) __weak FIRMessagingRmqManager *rmq2Manager; // @synthesize rmq2Manager=_rmq2Manager;
@property(retain, nonatomic) NSString *senderId; // @synthesize senderId=_senderId;
@property(retain, nonatomic) FIRMessagingRegistrar *registrar; // @synthesize registrar=_registrar;
@property(nonatomic) __weak id <FIRMessagingClientDelegate> clientDelegate; // @synthesize clientDelegate=_clientDelegate;
@property(nonatomic) __weak FIRMessagingDataMessageManager *dataMessageManager; // @synthesize dataMessageManager=_dataMessageManager;
@property(retain, nonatomic) FIRMessagingConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (unsigned int)nextRetryInterval;
- (void)scheduleConnectRetry;
- (void)didConnectTimeout;
- (void)tryToConnect;
- (void)setupConnection;
- (void)setupConnectionAndConnect;
- (int)connectionDidReceiveAckForRmqIds:(id)arg1;
- (void)connectionDidRecieveMessage:(id)arg1;
- (void)didLoginWithConnection:(id)arg1;
- (void)connection:(id)arg1 didCloseForReason:(unsigned int)arg2;
- (void)sendOnConnectOrDrop:(id)arg1;
- (void)sendMessage:(id)arg1;
- (void)checkinFetched:(id)arg1;
- (void)disconnectWithTryToConnectLater:(BOOL)arg1;
- (void)disconnect;
- (void)connect;
- (void)connectWithHandler:(CDUnknownBlockType)arg1;
- (void)retryConnectionImmediately:(BOOL)arg1;
@property(readonly, nonatomic) BOOL shouldStayConnected;
@property(readonly, nonatomic) BOOL isConnectionActive;
@property(readonly, nonatomic) BOOL isConnected;
- (void)updateSubscriptionWithToken:(id)arg1 topic:(id)arg2 options:(id)arg3 shouldDelete:(BOOL)arg4 handler:(CDUnknownBlockType)arg5;
- (void)cancelAllRequests;
- (void)teardown;
- (id)initWithDelegate:(id)arg1 reachability:(id)arg2 rmq2Manager:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

