//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface FormCell : UITableViewCell
{
    UILabel *_text;
    UIImageView *_check;
}

@property(nonatomic) __weak UIImageView *check; // @synthesize check=_check;
@property(nonatomic) __weak UILabel *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

