//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GtalkExtension, NSString;

@interface GtalkErrorInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int code; // @dynamic code;
@property(retain, nonatomic) GtalkExtension *extension; // @dynamic extension;
@property(nonatomic) BOOL hasCode; // @dynamic hasCode;
@property(nonatomic) BOOL hasExtension; // @dynamic hasExtension;
@property(nonatomic) BOOL hasMessage; // @dynamic hasMessage;
@property(nonatomic) BOOL hasType; // @dynamic hasType;
@property(copy, nonatomic) NSString *message; // @dynamic message;
@property(copy, nonatomic) NSString *type; // @dynamic type;

@end

