//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface GtalkIdle : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) BOOL away; // @dynamic away;
@property(nonatomic) BOOL hasAway; // @dynamic hasAway;
@property(nonatomic) BOOL hasIdle; // @dynamic hasIdle;
@property(nonatomic) BOOL idle; // @dynamic idle;

@end

