//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CustomActivityIndicator, LoginViewController, UIButton, UILabel, UIView;

@interface LoginPopupViewController : UIViewController
{
    CustomActivityIndicator *loading;
    LoginViewController *lvc;
    BOOL _login;
    UIView *_blurView;
    UIView *_contentView;
    UILabel *_text;
    UIButton *_buttonOk;
    UIButton *_buttonCancel;
}

@property(nonatomic) __weak UIButton *buttonCancel; // @synthesize buttonCancel=_buttonCancel;
@property(nonatomic) __weak UIButton *buttonOk; // @synthesize buttonOk=_buttonOk;
@property(nonatomic) __weak UILabel *text; // @synthesize text=_text;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *blurView; // @synthesize blurView=_blurView;
@property(nonatomic) BOOL login; // @synthesize login=_login;
- (void).cxx_destruct;
- (void)clickedCancel:(id)arg1;
- (void)clickedOk:(id)arg1;
- (void)showWithImage:(id)arg1;
- (void)viewDidLoad;

@end

