//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface NoDataCell : UITableViewCell
{
    UILabel *_reason;
}

@property(nonatomic) __weak UILabel *reason; // @synthesize reason=_reason;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

