//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface Notifications : NSObject
{
    NSMutableDictionary *_pushNotifications;
    NSMutableDictionary *_geoNotifications;
    double _lastUpdate;
}

+ (id)notifications;
@property(retain, nonatomic) NSMutableDictionary *geoNotifications; // @synthesize geoNotifications=_geoNotifications;
@property(retain, nonatomic) NSMutableDictionary *pushNotifications; // @synthesize pushNotifications=_pushNotifications;
@property(nonatomic) double lastUpdate; // @synthesize lastUpdate=_lastUpdate;
- (void).cxx_destruct;
- (BOOL)canNotifyGeoPushForOffer:(id)arg1;
- (id)newGeoNotification;
- (int)countOfNewNotifications;
- (void)setNotNewForNotification:(id)arg1;
- (id)sortedNotifications;
- (void)updateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)save;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

