//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIWebViewDelegate.h"

@class NSString, UILabel, UIWebView;

@interface OfferDetailDescriptionCell : UITableViewCell <UIWebViewDelegate>
{
    UILabel *_header;
    UIWebView *_content;
}

@property(nonatomic) __weak UIWebView *content; // @synthesize content=_content;
@property(nonatomic) __weak UILabel *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

