//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface OfferDetailHeaderCell : UITableViewCell
{
    UIImageView *_image;
    UIImageView *_imagePartner;
    UILabel *_text;
    UILabel *_discount;
    UIView *_discountView;
    UIButton *_buttonClaim;
}

@property(nonatomic) __weak UIButton *buttonClaim; // @synthesize buttonClaim=_buttonClaim;
@property(nonatomic) __weak UIView *discountView; // @synthesize discountView=_discountView;
@property(nonatomic) __weak UILabel *discount; // @synthesize discount=_discount;
@property(nonatomic) __weak UILabel *text; // @synthesize text=_text;
@property(nonatomic) __weak UIImageView *imagePartner; // @synthesize imagePartner=_imagePartner;
@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

