//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIView;

@interface OfferDetailCodesCell : UITableViewCell
{
    UILabel *_header;
    UIView *_content;
}

@property(nonatomic) __weak UIView *content; // @synthesize content=_content;
@property(nonatomic) __weak UILabel *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

