//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Description;

@interface OfferDetailCellContainer : NSObject
{
    Description *_desc;
    int _type;
    float _height;
    float _expandHeight;
}

@property(nonatomic) float expandHeight; // @synthesize expandHeight=_expandHeight;
@property(nonatomic) float height; // @synthesize height=_height;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) Description *desc; // @synthesize desc=_desc;
- (void).cxx_destruct;
- (id)init;

@end

