//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIImageView, WrongVersionViewController;

@interface SplashViewController : UIViewController
{
    float total;
    float progress;
    int lastImage;
    WrongVersionViewController *wvvc;
    UIImageView *_image;
}

@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (int)preferredStatusBarStyle;
- (BOOL)prefersStatusBarHidden;
- (void)checkVersion;
- (void)update;
- (void)stopAnimating;
- (void)endAnimate;
- (void)makeProgress;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

