//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface StaticData : NSObject
{
    int _gpsUpdateFrequency;
    int _dailyGeoPerOffer;
    int _dailyGeoTotal;
    NSString *_about;
    NSString *_forceUpdate;
    NSString *_legalHeader;
    NSString *_legalSubheader;
    NSString *_legalAppText;
    NSString *_legalAppLink;
    NSString *_legalAppLinkText;
    NSString *_legalMktText;
    NSString *_legalMktLink;
    NSString *_legalMktLinkText;
    NSString *_legalNavText;
    NSString *_legalNavLink;
    NSString *_legalNavLinkText;
    NSMutableDictionary *_form;
    NSMutableDictionary *_navigation;
    NSMutableDictionary *_tripTexts;
    double _lastUpdate;
}

+ (id)data;
@property(retain, nonatomic) NSMutableDictionary *tripTexts; // @synthesize tripTexts=_tripTexts;
@property(retain, nonatomic) NSMutableDictionary *navigation; // @synthesize navigation=_navigation;
@property(retain, nonatomic) NSMutableDictionary *form; // @synthesize form=_form;
@property(retain, nonatomic) NSString *legalNavLinkText; // @synthesize legalNavLinkText=_legalNavLinkText;
@property(retain, nonatomic) NSString *legalNavLink; // @synthesize legalNavLink=_legalNavLink;
@property(retain, nonatomic) NSString *legalNavText; // @synthesize legalNavText=_legalNavText;
@property(retain, nonatomic) NSString *legalMktLinkText; // @synthesize legalMktLinkText=_legalMktLinkText;
@property(retain, nonatomic) NSString *legalMktLink; // @synthesize legalMktLink=_legalMktLink;
@property(retain, nonatomic) NSString *legalMktText; // @synthesize legalMktText=_legalMktText;
@property(retain, nonatomic) NSString *legalAppLinkText; // @synthesize legalAppLinkText=_legalAppLinkText;
@property(retain, nonatomic) NSString *legalAppLink; // @synthesize legalAppLink=_legalAppLink;
@property(retain, nonatomic) NSString *legalAppText; // @synthesize legalAppText=_legalAppText;
@property(retain, nonatomic) NSString *legalSubheader; // @synthesize legalSubheader=_legalSubheader;
@property(retain, nonatomic) NSString *legalHeader; // @synthesize legalHeader=_legalHeader;
@property(retain, nonatomic) NSString *forceUpdate; // @synthesize forceUpdate=_forceUpdate;
@property(retain, nonatomic) NSString *about; // @synthesize about=_about;
@property(nonatomic) int dailyGeoTotal; // @synthesize dailyGeoTotal=_dailyGeoTotal;
@property(nonatomic) int dailyGeoPerOffer; // @synthesize dailyGeoPerOffer=_dailyGeoPerOffer;
@property(nonatomic) int gpsUpdateFrequency; // @synthesize gpsUpdateFrequency=_gpsUpdateFrequency;
@property(nonatomic) double lastUpdate; // @synthesize lastUpdate=_lastUpdate;
- (void).cxx_destruct;
- (void)updateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)save;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

