//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSArray, NSString, UILabel, UIView;

@interface SygicNoDataViewController : UIViewController
{
    NSArray *_reasonsWhyNot;
    UIView *_blurView;
    UIView *_contentView;
    UILabel *_label1;
    UILabel *_label2;
    UIView *_shadowView;
    UIView *_roundedView;
    UIView *_claimButtonView;
    UILabel *_reasonsLabel;
    NSString *_message;
}

@property(retain) NSString *message; // @synthesize message=_message;
@property(nonatomic) __weak UILabel *reasonsLabel; // @synthesize reasonsLabel=_reasonsLabel;
@property(nonatomic) __weak UIView *claimButtonView; // @synthesize claimButtonView=_claimButtonView;
@property(nonatomic) __weak UIView *roundedView; // @synthesize roundedView=_roundedView;
@property(nonatomic) __weak UIView *shadowView; // @synthesize shadowView=_shadowView;
@property(nonatomic) __weak UILabel *label2; // @synthesize label2=_label2;
@property(nonatomic) __weak UILabel *label1; // @synthesize label1=_label1;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *blurView; // @synthesize blurView=_blurView;
@property(retain) NSArray *reasonsWhyNot; // @synthesize reasonsWhyNot=_reasonsWhyNot;
- (void).cxx_destruct;
- (void)clickedBack:(id)arg1;
- (void)showWithImage:(id)arg1;
- (void)setupButtons;
- (void)setupLabels;
- (void)viewDidLoad;

@end

