//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SygicIcons : NSObject
{
}

+ (id)directionIconForManeuver:(id)arg1 foreground:(BOOL)arg2;
+ (id)poiIconForResult:(id)arg1;

@end

