//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SYAnnotation, SYAnnotationView, SYGeoCoordinate, SYMapView;

@protocol SYMapViewDelegate <NSObject>

@optional
- (void)mapViewDidStopMoving:(SYMapView *)arg1;
- (SYAnnotationView *)mapView:(SYMapView *)arg1 viewForAnnotation:(SYAnnotation *)arg2;
- (void)mapView:(SYMapView *)arg1 didSelectObjects:(NSArray *)arg2;
- (void)mapView:(SYMapView *)arg1 didChangeCameraRotationMode:(int)arg2;
- (void)mapView:(SYMapView *)arg1 didChangeCameraMovementMode:(int)arg2;
- (void)mapView:(SYMapView *)arg1 didChangeCameraPosition:(SYGeoCoordinate *)arg2 zoom:(float)arg3 rotation:(float)arg4 tilt:(float)arg5;
@end

