//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SYAlternativeRoute, SYInstruction, SYLanesInformation, SYNavigation, SYOnRouteInfo, SYPositionInfo, SYRadar, SYRailwayCrossing, SYRoute, SYSharpCurve, SYSpeedLimit;

@protocol SYNavigationDelegate <NSObject>

@optional
- (void)navigation:(SYNavigation *)arg1 didUpdateLanesInformation:(SYLanesInformation *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateOnRouteInfo:(SYOnRouteInfo *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateTransportMode:(int)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdatePois:(NSArray *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdatePoisOnRoute:(NSArray *)arg2 withProgress:(float)arg3;
- (void)navigation:(SYNavigation *)arg1 didUpdateRadars:(NSArray *)arg2 onRoute:(SYRoute *)arg3;
- (void)navigation:(SYNavigation *)arg1 didUpdateRoute:(SYRoute *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateHighwayExit:(NSArray *)arg2;
- (void)navigation:(SYNavigation *)arg1 didFindBetterRoute:(SYAlternativeRoute *)arg2;
- (void)navigationManagerDidReachFinish:(SYNavigation *)arg1;
- (void)navigation:(SYNavigation *)arg1 didPassWaypointWithIndex:(unsigned int)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateSharpCurve:(SYSharpCurve *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateRailwayCrossing:(SYRailwayCrossing *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateRadar:(SYRadar *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateSignpost:(NSArray *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateDirection:(SYInstruction *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdateSpeedLimit:(SYSpeedLimit *)arg2;
- (void)navigation:(SYNavigation *)arg1 didUpdatePositionInfo:(SYPositionInfo *)arg2;
@end

