//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SYRoute, SYRouteInfo, SYRouting;

@protocol SYRoutingDelegate <NSObject>

@optional
- (void)routing:(SYRouting *)arg1 recomputingFailedWithError:(int)arg2;
- (void)routing:(SYRouting *)arg1 didFinishRouteRecompute:(SYRoute *)arg2;
- (void)routing:(SYRouting *)arg1 didComputeDurations:(NSArray *)arg2 for:(SYRoute *)arg3;
- (void)routingDidStartRouteRecompute:(SYRouting *)arg1;
- (void)routing:(SYRouting *)arg1 didComputeRouteInfo:(SYRouteInfo *)arg2;
- (void)routingDidFinishRouteCompute:(SYRouting *)arg1;
- (void)routing:(SYRouting *)arg1 computingFailedWithError:(int)arg2;
- (void)routing:(SYRouting *)arg1 didComputeAlternativeRoute:(SYRoute *)arg2;
- (void)routing:(SYRouting *)arg1 didComputePrimaryRoute:(SYRoute *)arg2;
- (void)routingDidStartRouteComputing:(SYRouting *)arg1;
- (void)routing:(SYRouting *)arg1 didUpdateComputingProgress:(float)arg2 onRoute:(unsigned int)arg3;
@end

