//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CustomActivityIndicator, UIButton, UILabel, UIView;

@interface AgreementsViewController : UIViewController
{
    BOOL marketing;
    BOOL terms;
    CustomActivityIndicator *loading;
    UIView *_blurView;
    UIView *_contentView;
    UILabel *_header;
    UILabel *_subheader;
    UIView *_termsView;
    UIView *_marketingView;
    UILabel *_textMarketing;
    UILabel *_textTerms;
    UIButton *_buttonMarketing;
    UIButton *_buttonTerms;
    UIButton *_buttonOk;
    UIButton *_buttonClose;
}

@property(nonatomic) __weak UIButton *buttonClose; // @synthesize buttonClose=_buttonClose;
@property(nonatomic) __weak UIButton *buttonOk; // @synthesize buttonOk=_buttonOk;
@property(nonatomic) __weak UIButton *buttonTerms; // @synthesize buttonTerms=_buttonTerms;
@property(nonatomic) __weak UIButton *buttonMarketing; // @synthesize buttonMarketing=_buttonMarketing;
@property(nonatomic) __weak UILabel *textTerms; // @synthesize textTerms=_textTerms;
@property(nonatomic) __weak UILabel *textMarketing; // @synthesize textMarketing=_textMarketing;
@property(nonatomic) __weak UIView *marketingView; // @synthesize marketingView=_marketingView;
@property(nonatomic) __weak UIView *termsView; // @synthesize termsView=_termsView;
@property(nonatomic) __weak UILabel *subheader; // @synthesize subheader=_subheader;
@property(nonatomic) __weak UILabel *header; // @synthesize header=_header;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *blurView; // @synthesize blurView=_blurView;
- (void).cxx_destruct;
- (void)hide;
- (void)setAgreements;
- (void)tappedTerms:(id)arg1;
- (void)tappedMarketing:(id)arg1;
- (void)clickedTerms;
- (void)clickedMarketing;
- (void)setButtons;
- (void)clickedClose:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)showWithImage:(id)arg1;
- (void)viewDidLoad;

@end

