//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class NSString, UIColor, UIFont, UILabel, UITextView;

@interface AnimatedTextview : UIView <UITextViewDelegate>
{
    UITextView *textView;
    UILabel *textViewPlaceholder;
    UILabel *atPlaceholder;
    UIView *activityIndicator;
    UIFont *atTextFont;
    UIColor *atTextColor;
    UIFont *atPlaceholderFont;
    UIColor *atPlaceholderColor;
    UIColor *atActivityIndicatorOffColor;
    UIColor *atActivityIndicatorOnColor;
    id <AnimatedTextviewDelegate> _delegate;
}

@property(nonatomic) __weak id <AnimatedTextviewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)clickOnView;
- (void)calculateViews:(BOOL)arg1;
- (void)hidePlaceholderAnimated:(BOOL)arg1;
- (void)showPlaceholderAnimated:(BOOL)arg1;
- (void)resignFirstResponder;
- (void)becomeFirstResponder;
- (id)text;
- (void)setActivityIndicatorHeight:(float)arg1;
- (void)setActivityIndicatorOnColor:(id)arg1;
- (void)setActivityIndicatorOffColor:(id)arg1;
- (void)setPlaceholderFont:(id)arg1;
- (void)setPlaceholderColor:(id)arg1;
- (void)setPlaceholder:(id)arg1;
- (void)setTextFont:(id)arg1;
- (void)setTextColor:(id)arg1;
- (void)setText:(id)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

