//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSURL;

@interface ANSCleanupFilesOperation : NSOperation
{
    CDUnknownBlockType _successBlock;
    NSURL *_directoryUrl;
    int _maximumPendingMultipartFiles;
}

@property(readonly, nonatomic) int maximumPendingMultipartFiles; // @synthesize maximumPendingMultipartFiles=_maximumPendingMultipartFiles;
@property(readonly, nonatomic) NSURL *directoryUrl; // @synthesize directoryUrl=_directoryUrl;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
- (void).cxx_destruct;
- (id)URLsByRemovingOldFiles:(id)arg1 withMaximumFileCount:(int)arg2;
- (void)main;
- (id)initWithDirectoryURL:(id)arg1 maximumPendingMulitpartFiles:(int)arg2;

@end

