//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ANSEvent.h"

@class NSDate;

@interface ANSCrashEvent : ANSEvent
{
    NSDate *_crashTimestamp;
    unsigned int _crashState;
}

@property(nonatomic) unsigned int crashState; // @synthesize crashState=_crashState;
@property(retain, nonatomic) NSDate *crashTimestamp; // @synthesize crashTimestamp=_crashTimestamp;
- (void).cxx_destruct;
- (id)payloadStringForCrashState:(unsigned int)arg1;
- (id)dictionaryRepresentation;
- (id)timestamp;
- (id)name;
- (id)initWithTimestamp:(id)arg1 crashState:(unsigned int)arg2;

@end

