//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ASIdentifierManager, NSString;

@interface APMASIdentifierManager : NSObject
{
    ASIdentifierManager *_sharedIdentifierManager;
}

+ (id)sharedManager;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)advertisingIdentifier;
- (BOOL)isAdvertisingTrackingEnabled;
@property(readonly, nonatomic) BOOL limitedAdTracking;
@property(readonly, nonatomic) BOOL hasLimitedAdTracking;
@property(readonly, nonatomic) NSString *advertisingIdentifierString;
- (id)initWithIdentifierManager:(id)arg1;

@end

