//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class APMPersistedConfig, APMSqliteStore;

@interface APMDatabase : NSObject
{
    APMSqliteStore *_sqliteStore;
    APMPersistedConfig *_persistedConfig;
}

- (void).cxx_destruct;
- (BOOL)updateDataType:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 error:(id *)arg5 createDictionaryBlock:(CDUnknownBlockType)arg6;
- (BOOL)upsertDataType:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 tableLimit:(int)arg5 error:(id *)arg6 createDictionaryBlock:(CDUnknownBlockType)arg7;
- (BOOL)insertDataType:(id)arg1 inTableWithName:(id)arg2 error:(id *)arg3 createDictionaryBlock:(CDUnknownBlockType)arg4;
- (id)dataTypesFromTableWithName:(id)arg1 columnName:(id)arg2 columnValue:(id)arg3 error:(id *)arg4 createDataTypeBlock:(CDUnknownBlockType)arg5;
- (id)allDataTypesFromTableWithName:(id)arg1 tableLimit:(int)arg2 error:(id *)arg3 createDataTypeBlock:(CDUnknownBlockType)arg4;
- (BOOL)ensureAllTables;
- (BOOL)initializeDatabaseResourcesWithContext:(id)arg1 databasePath:(id)arg2;
- (BOOL)deleteComplexEventForAudienceEvaluationWithEventID:(long long)arg1 error:(id *)arg2;
- (BOOL)updateComplexEventForAudienceEvaluationWithEventID:(long long)arg1 childEventCount:(long long)arg2 mainEvent:(id)arg3 error:(id *)arg4;
- (id)mainEventAndChildCountPairWithEventID:(long long)arg1 error:(id *)arg2;
- (id)conditionalUserPropertiesWithCondition:(id)arg1 parameterValues:(id)arg2 error:(id *)arg3;
- (id)conditionalUserPropertiesWithPrefix:(id)arg1 filterByOrigin:(id)arg2 error:(id *)arg3;
- (id)triggeredConditionalUserPropertiesWithEventName:(id)arg1 error:(id *)arg2;
- (id)expiredConditionalUserPropertiesWithError:(id *)arg1;
- (id)timedOutConditionalUserPropertiesWithError:(id *)arg1;
- (BOOL)deleteConditionalUserPropertyWithName:(id)arg1 error:(id *)arg2;
- (BOOL)updateConditionalUserProperty:(id)arg1 error:(id *)arg2;
- (id)conditionalUserPropertyWithName:(id)arg1 error:(id *)arg2;
- (id)insertIfNotDuplicatePurchaseFingerprint:(id)arg1 error:(id *)arg2;
- (id)lastRemoteConfigUpdateTimestamp:(id *)arg1;
- (id)queryMeasurementConfigWithError:(id *)arg1;
- (BOOL)updateRemoteConfigSuccessfulTimestamp:(double)arg1 error:(id *)arg2;
- (BOOL)updateRemoteConfig:(id)arg1 error:(id *)arg2;
- (BOOL)deleteAllPropertyFilters:(id *)arg1;
- (BOOL)deleteAllEventFilters:(id *)arg1;
- (BOOL)deletePropertyFilters:(id)arg1 error:(id *)arg2;
- (BOOL)deleteEventFilters:(id)arg1 error:(id *)arg2;
- (BOOL)updateFilterResults:(id)arg1 error:(id *)arg2;
- (BOOL)updatePropertyFilters:(id)arg1 error:(id *)arg2;
- (BOOL)updateEventFilters:(id)arg1 error:(id *)arg2;
- (id)allSessionScopedFilters:(id *)arg1;
- (BOOL)deleteFilterResults:(id)arg1 error:(id *)arg2;
- (id)filterResultForAudienceID:(int)arg1 error:(id *)arg2;
- (id)propertyFiltersForPropertyName:(id)arg1 error:(id *)arg2;
- (id)eventFiltersForEventName:(id)arg1 error:(id *)arg2;
- (id)allAudienceIDs:(id *)arg1;
- (id)allFilterResults:(id *)arg1;
- (BOOL)deleteUserAttributeWithName:(id)arg1 error:(id *)arg2;
- (BOOL)updateUserAttribute:(id)arg1 error:(id *)arg2;
- (id)userAttributesIncludingInternal:(BOOL)arg1 error:(id *)arg2;
- (id)allLifetimeValueUserAttributes:(id *)arg1;
- (id)userAttributeWithName:(id)arg1 error:(id *)arg2;
- (id)containsUserAttributeWithName:(id)arg1 error:(id *)arg2;
- (id)userAttributeCountForOrigin:(id)arg1 error:(id *)arg2;
- (id)publicUserAttributeCount:(id *)arg1;
- (BOOL)updateEventAggregates:(id)arg1 error:(id *)arg2;
- (id)eventAggregatesWithName:(id)arg1 error:(id *)arg2;
- (id)allEventAggregates:(id *)arg1;
- (id)publicEventCount:(id *)arg1;
- (id)containsRealtimeBundlesWithError:(id *)arg1;
- (id)queryLatestBundleTime:(id *)arg1;
- (BOOL)deleteStaleBundlesOlderThanMaxAge:(double)arg1 error:(id *)arg2;
- (id)maybeDeleteStaleData:(id *)arg1;
- (BOOL)deleteBundlesWithRowIDs:(id)arg1 error:(id *)arg2;
- (id)queryBundlesWithRowIDs:(id)arg1 error:(id *)arg2;
- (id)queryBundlesWithCountLimit:(long long)arg1 sizeLimit:(long long)arg2 error:(id *)arg3;
- (BOOL)incrementRetryCounterForBundlesWithIDs:(id)arg1 error:(id *)arg2;
- (BOOL)insertBundle:(id)arg1 isRealtime:(BOOL)arg2 error:(id *)arg3;
- (id)isQueuedBundleTableEmpty:(id *)arg1;
- (id)containsRealtimeRawEventsWithError:(id *)arg1;
- (id)rawEventDataFromDictionary:(id)arg1 error:(id *)arg2;
- (id)nextMetadataFingerprintToProcess:(id *)arg1;
- (BOOL)deleteStaleRawEventsDataOlderThanMaxAge:(double)arg1 error:(id *)arg2;
- (id)deleteRawEventsOverAbsoluteLimit:(id *)arg1;
- (BOOL)deleteRawEventsWithMaxRowID:(long long)arg1 error:(id *)arg2;
- (id)containsRawEventWithMetadataFingerprint:(long long)arg1 error:(id *)arg2;
- (id)rawEventsWithMetadataFingerprint:(long long)arg1 error:(id *)arg2 eventFilter:(CDUnknownBlockType)arg3;
- (id)queryLatestRawEventTime:(id *)arg1;
- (BOOL)insertRawEvent:(id)arg1 metadataFingerprint:(long long)arg2 isRealtime:(BOOL)arg3 error:(id *)arg4;
- (id)isRawEventsTableEmpty:(id *)arg1;
- (BOOL)deleteUnusedRawEventsMetadata:(id *)arg1;
- (BOOL)deleteRawEventMetadataWithMetadataFingerprint:(long long)arg1 error:(id *)arg2;
- (id)queryRawEventsMetadataWithFingerprint:(long long)arg1 error:(id *)arg2;
- (BOOL)insertIfNotExistsRawEventMetadata:(id)arg1 error:(id *)arg2;
- (BOOL)updateDailyCounts:(id)arg1 error:(id *)arg2;
- (id)dailyCounts:(id *)arg1;
- (BOOL)updateAppMetadata:(id)arg1 error:(id *)arg2;
- (id)queryAppMetadata:(id *)arg1;
- (BOOL)initializeAppMetadata;
- (BOOL)performTransaction:(CDUnknownBlockType)arg1;
- (void)reset;
- (id)initWithDatabaseName:(id)arg1 persistedConfig:(id)arg2;

@end

