//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APMLifetimeValueRecorder : NSObject
{
}

+ (BOOL)isPurchaseEvent:(id)arg1;
+ (BOOL)recordLifetimeValueToDatabase:(id)arg1 event:(id)arg2;

@end

