//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface CodeCell : UITableViewCell
{
    UIImageView *_imageOffer;
    UIImageView *_imagePartner;
    UILabel *_name;
    UILabel *_date;
    UILabel *_code;
}

@property(nonatomic) __weak UILabel *code; // @synthesize code=_code;
@property(nonatomic) __weak UILabel *date; // @synthesize date=_date;
@property(nonatomic) __weak UILabel *name; // @synthesize name=_name;
@property(nonatomic) __weak UIImageView *imagePartner; // @synthesize imagePartner=_imagePartner;
@property(nonatomic) __weak UIImageView *imageOffer; // @synthesize imageOffer=_imageOffer;
- (void).cxx_destruct;

@end

