//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface Codes : NSObject
{
    NSMutableDictionary *_list;
    double _lastUpdate;
}

+ (id)codes;
@property(retain, nonatomic) NSMutableDictionary *list; // @synthesize list=_list;
@property(nonatomic) double lastUpdate; // @synthesize lastUpdate=_lastUpdate;
- (void).cxx_destruct;
- (id)sortedCodesForOffer:(id)arg1;
- (id)sortedCodes;
- (void)updateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)save;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

