//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFMessageComposeViewControllerDelegate.h"

@class NSString, UILabel, UIView;

@interface DataCodeDetailViewController : UIViewController <MFMessageComposeViewControllerDelegate>
{
    int number;
    NSString *_code;
    UILabel *_label1;
    UILabel *_label2;
    UILabel *_codeLabel;
    UILabel *_numberLabel;
    UIView *_smsButtonView;
}

@property(nonatomic) __weak UIView *smsButtonView; // @synthesize smsButtonView=_smsButtonView;
@property(nonatomic) __weak UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(nonatomic) __weak UILabel *codeLabel; // @synthesize codeLabel=_codeLabel;
@property(nonatomic) __weak UILabel *label2; // @synthesize label2=_label2;
@property(nonatomic) __weak UILabel *label1; // @synthesize label1=_label1;
@property(retain) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (void)hide;
- (void)show;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)clickedSendSMS:(id)arg1;
- (void)clickedBackToNav:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)setupLabels;
- (void)setupButtons;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

