//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EVGPS : NSObject
{
    NSString *_Id;
    NSString *_name;
    int _radius;
    NSString *_region;
    double _latitude;
    double _longitude;
    double _notifiedAt;
}

@property(nonatomic) double notifiedAt; // @synthesize notifiedAt=_notifiedAt;
@property(retain, nonatomic) NSString *region; // @synthesize region=_region;
@property(nonatomic) int radius; // @synthesize radius=_radius;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *Id; // @synthesize Id=_Id;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

