//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRMessagingCheckinService, FIRMessagingPubSubRegistrar, NSString;

@interface FIRMessagingRegistrar : NSObject
{
    BOOL _stopAllSubscriptions;
    FIRMessagingPubSubRegistrar *_pubsubRegistrar;
    FIRMessagingCheckinService *_checkinService;
}

@property(retain, nonatomic) FIRMessagingCheckinService *checkinService; // @synthesize checkinService=_checkinService;
@property(nonatomic) BOOL stopAllSubscriptions; // @synthesize stopAllSubscriptions=_stopAllSubscriptions;
@property(retain, nonatomic) FIRMessagingPubSubRegistrar *pubsubRegistrar; // @synthesize pubsubRegistrar=_pubsubRegistrar;
- (void).cxx_destruct;
- (void)doUpdateSubscriptionForTopic:(id)arg1 token:(id)arg2 options:(id)arg3 shouldDelete:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
- (void)cancelAllRequests;
- (void)updateSubscriptionToTopic:(id)arg1 withToken:(id)arg2 options:(id)arg3 shouldDelete:(BOOL)arg4 handler:(CDUnknownBlockType)arg5;
- (BOOL)tryToLoadValidCheckinInfo;
- (id)init;
@property(readonly, nonatomic) NSString *secretToken;
@property(readonly, nonatomic) NSString *deviceAuthID;

@end

