//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FIRMessagingRmq2PersistentStore : NSObject
{
    struct sqlite3 *_database;
    NSString *_databaseName;
    unsigned int _currentDirectory;
}

+ (void)removeDatabase:(id)arg1;
+ (id)pathForDatabase:(id)arg1 inDirectory:(unsigned int)arg2;
@property(nonatomic) unsigned int currentDirectory; // @synthesize currentDirectory=_currentDirectory;
@property(retain, nonatomic) NSString *databaseName; // @synthesize databaseName=_databaseName;
- (void).cxx_destruct;
- (void)logErrorAndFinalizeStatement:(struct sqlite3_stmt *)arg1;
- (void)logError;
- (int)lastErrorCode;
- (id)lastErrorMessage;
- (BOOL)updateSyncMessageWithRmqID:(id)arg1 column:(id)arg2 value:(BOOL)arg3 error:(id *)arg4;
- (BOOL)updateSyncMessageViaMCSWithRmqID:(id)arg1 error:(id *)arg2;
- (BOOL)updateSyncMessageViaAPNSWithRmqID:(id)arg1 error:(id *)arg2;
- (BOOL)saveSyncMessageWithRmqID:(id)arg1 expirationTime:(long long)arg2 apnsReceived:(BOOL)arg3 mcsReceived:(BOOL)arg4 error:(id *)arg5;
- (int)deleteExpiredOrFinishedSyncMessages:(id *)arg1;
- (BOOL)deleteSyncMessageWithRmqID:(id)arg1;
- (id)querySyncMessageWithRmqID:(id)arg1;
- (void)scanOutgoingRmqMessagesWithHandler:(CDUnknownBlockType)arg1;
- (id)unackedS2dRmqIds;
- (BOOL)updateLastOutgoingRmqId:(long long)arg1;
- (long long)queryLastRmqId;
- (long long)queryHighestRmqId;
- (int)deleteMessagesFromTable:(id)arg1 withRmqIds:(id)arg2;
- (BOOL)saveMessageWithRmqId:(long long)arg1 tag:(BOOL)arg2 data:(id)arg3 error:(id *)arg4;
- (BOOL)saveUnackedS2dMessageWithRmqId:(id)arg1;
- (void)updateDbWithStringRmqID;
- (void)openDatabase:(id)arg1;
- (void)removeDatabase;
- (void)dropTableWithName:(id)arg1;
- (void)createTableWithName:(id)arg1 command:(id)arg2;
- (BOOL)doesFileExistInDirectory:(unsigned int)arg1;
- (BOOL)moveToApplicationSupportSubDirectory:(id)arg1;
- (void)dealloc;
- (id)initWithDatabaseName:(id)arg1;

@end

