//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class FIRMessagingPacketQueue, NSInputStream, NSMutableData, NSOutputStream, NSRunLoop, NSString;

@interface FIRMessagingSecureSocket : NSObject <NSStreamDelegate>
{
    BOOL _isVersionSent;
    BOOL _isVersionReceived;
    BOOL _isInStreamOpen;
    BOOL _isOutStreamOpen;
    BOOL _currentProtoTypeBeingSent;
    id <FIRMessagingSecureSocketDelegate> _delegate;
    unsigned int _state;
    NSInputStream *_inStream;
    NSOutputStream *_outStream;
    NSMutableData *_inputBuffer;
    unsigned int _inputBufferLength;
    NSMutableData *_outputBuffer;
    unsigned int _outputBufferLength;
    FIRMessagingPacketQueue *_packetQueue;
    NSRunLoop *_runLoop;
    NSString *_currentRmqIdBeingSent;
}

@property(nonatomic) BOOL currentProtoTypeBeingSent; // @synthesize currentProtoTypeBeingSent=_currentProtoTypeBeingSent;
@property(retain, nonatomic) NSString *currentRmqIdBeingSent; // @synthesize currentRmqIdBeingSent=_currentRmqIdBeingSent;
@property(retain, nonatomic) NSRunLoop *runLoop; // @synthesize runLoop=_runLoop;
@property(nonatomic) BOOL isOutStreamOpen; // @synthesize isOutStreamOpen=_isOutStreamOpen;
@property(nonatomic) BOOL isInStreamOpen; // @synthesize isInStreamOpen=_isInStreamOpen;
@property(nonatomic) BOOL isVersionReceived; // @synthesize isVersionReceived=_isVersionReceived;
@property(nonatomic) BOOL isVersionSent; // @synthesize isVersionSent=_isVersionSent;
@property(retain, nonatomic) FIRMessagingPacketQueue *packetQueue; // @synthesize packetQueue=_packetQueue;
@property(nonatomic) unsigned int outputBufferLength; // @synthesize outputBufferLength=_outputBufferLength;
@property(retain, nonatomic) NSMutableData *outputBuffer; // @synthesize outputBuffer=_outputBuffer;
@property(nonatomic) unsigned int inputBufferLength; // @synthesize inputBufferLength=_inputBufferLength;
@property(retain, nonatomic) NSMutableData *inputBuffer; // @synthesize inputBuffer=_inputBuffer;
@property(retain, nonatomic) NSOutputStream *outStream; // @synthesize outStream=_outStream;
@property(retain, nonatomic) NSInputStream *inStream; // @synthesize inStream=_inStream;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
@property(nonatomic) __weak id <FIRMessagingSecureSocketDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)performWrite;
- (unsigned int)processCurrentInputBuffer:(id)arg1 outOffset:(unsigned int *)arg2;
- (BOOL)performRead;
- (void)closeStream:(id)arg1;
- (void)openStream:(id)arg1 isVOIPStream:(BOOL)arg2;
- (void)stream:(id)arg1 handleEvent:(unsigned int)arg2;
- (void)sendData:(id)arg1 withTag:(BOOL)arg2 rmqId:(id)arg3;
- (void)disconnect;
- (void)connectToHost:(id)arg1 port:(unsigned int)arg2 onRunLoop:(id)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

