//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface FIRMessagingCodedInputStream : NSObject
{
    NSData *_buffer;
    CDStruct_c37e13d3 _state;
}

@property(nonatomic) CDStruct_c37e13d3 state; // @synthesize state=_state;
@property(retain, nonatomic) NSData *buffer; // @synthesize buffer=_buffer;
- (void).cxx_destruct;
- (id)readDataWithLength:(unsigned int)arg1;
- (BOOL)readLength:(int *)arg1;
- (BOOL)readTag:(char *)arg1;
@property(readonly, nonatomic) unsigned long offset;
- (id)initWithData:(id)arg1;

@end

