//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class Question, UIButton, UILabel, UINavigationController;

@interface FormQuestionViewController : UIViewController
{
    int _index;
    Question *_question;
    UINavigationController *_nc;
    UILabel *_questionText;
    UIButton *_button1;
    UIButton *_button2;
    UIButton *_button3;
    UIButton *_button4;
    UIButton *_button5;
    UIButton *_button6;
    UIButton *_button7;
    UIButton *_button8;
    UIButton *_buttonLogin;
    UIButton *_buttonBack;
}

@property(nonatomic) __weak UIButton *buttonBack; // @synthesize buttonBack=_buttonBack;
@property(nonatomic) __weak UIButton *buttonLogin; // @synthesize buttonLogin=_buttonLogin;
@property(nonatomic) __weak UIButton *button8; // @synthesize button8=_button8;
@property(nonatomic) __weak UIButton *button7; // @synthesize button7=_button7;
@property(nonatomic) __weak UIButton *button6; // @synthesize button6=_button6;
@property(nonatomic) __weak UIButton *button5; // @synthesize button5=_button5;
@property(nonatomic) __weak UIButton *button4; // @synthesize button4=_button4;
@property(nonatomic) __weak UIButton *button3; // @synthesize button3=_button3;
@property(nonatomic) __weak UIButton *button2; // @synthesize button2=_button2;
@property(nonatomic) __weak UIButton *button1; // @synthesize button1=_button1;
@property(nonatomic) __weak UILabel *questionText; // @synthesize questionText=_questionText;
@property(retain, nonatomic) UINavigationController *nc; // @synthesize nc=_nc;
@property(retain, nonatomic) Question *question; // @synthesize question=_question;
@property(nonatomic) int index; // @synthesize index=_index;
- (void).cxx_destruct;
- (void)clickedButton8:(id)arg1;
- (void)clickedButton7:(id)arg1;
- (void)clickedButton6:(id)arg1;
- (void)clickedButton5:(id)arg1;
- (void)clickedButton4:(id)arg1;
- (void)clickedButton3:(id)arg1;
- (void)clickedButton2:(id)arg1;
- (void)clickedButton1:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)clickedClose:(id)arg1;
- (void)clickedLogin:(id)arg1;
- (void)refresh;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

