//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"
#import "UIAlertViewDelegate.h"

@class CLLocationManager, NSString;

@interface GPSService : NSObject <CLLocationManagerDelegate, UIAlertViewDelegate>
{
    CLLocationManager *manager;
    double timeForGetLocation;
    BOOL _started;
    id <GPSServiceDelegate> _delegate;
}

@property(nonatomic) BOOL started; // @synthesize started=_started;
@property(nonatomic) __weak id <GPSServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)receivedLocation:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)stopBackgroundTask;
- (void)startBackgroundTask;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

