//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GtalkOtrItem : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) BOOL changedByBuddy; // @dynamic changedByBuddy;
@property(nonatomic) BOOL hasChangedByBuddy; // @dynamic hasChangedByBuddy;
@property(nonatomic) BOOL hasJid; // @dynamic hasJid;
@property(nonatomic) BOOL hasNosave; // @dynamic hasNosave;
@property(copy, nonatomic) NSString *jid; // @dynamic jid;
@property(nonatomic) BOOL nosave; // @dynamic nosave;

@end

