//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GtalkRosterItem : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int ask; // @dynamic ask;
@property(nonatomic) int display; // @dynamic display;
@property(retain, nonatomic) NSMutableArray *groupArray; // @dynamic groupArray;
@property(readonly, nonatomic) unsigned int groupArray_Count; // @dynamic groupArray_Count;
@property(nonatomic) BOOL hasAsk; // @dynamic hasAsk;
@property(nonatomic) BOOL hasDisplay; // @dynamic hasDisplay;
@property(nonatomic) BOOL hasJid; // @dynamic hasJid;
@property(nonatomic) BOOL hasName; // @dynamic hasName;
@property(nonatomic) BOOL hasQuickContact; // @dynamic hasQuickContact;
@property(nonatomic) BOOL hasRejected; // @dynamic hasRejected;
@property(nonatomic) BOOL hasSubscription; // @dynamic hasSubscription;
@property(copy, nonatomic) NSString *jid; // @dynamic jid;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) BOOL quickContact; // @dynamic quickContact;
@property(nonatomic) BOOL rejected; // @dynamic rejected;
@property(nonatomic) int subscription; // @dynamic subscription;

@end

