//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GtalkSharedStatus : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) BOOL hasInvisible; // @dynamic hasInvisible;
@property(nonatomic) BOOL hasShow; // @dynamic hasShow;
@property(nonatomic) BOOL hasStatus; // @dynamic hasStatus;
@property(nonatomic) BOOL hasStatusListContentsMax; // @dynamic hasStatusListContentsMax;
@property(nonatomic) BOOL hasStatusListMax; // @dynamic hasStatusListMax;
@property(nonatomic) BOOL hasStatusMax; // @dynamic hasStatusMax;
@property(nonatomic) BOOL hasStatusMinVersion; // @dynamic hasStatusMinVersion;
@property(nonatomic) BOOL invisible; // @dynamic invisible;
@property(nonatomic) int show; // @dynamic show;
@property(copy, nonatomic) NSString *status; // @dynamic status;
@property(retain, nonatomic) NSMutableArray *statusListArray; // @dynamic statusListArray;
@property(readonly, nonatomic) unsigned int statusListArray_Count; // @dynamic statusListArray_Count;
@property(nonatomic) int statusListContentsMax; // @dynamic statusListContentsMax;
@property(nonatomic) int statusListMax; // @dynamic statusListMax;
@property(nonatomic) int statusMax; // @dynamic statusMax;
@property(nonatomic) int statusMinVersion; // @dynamic statusMinVersion;

@end

