//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GtalkCellTower, NSData, NSMutableArray, NSString;

@interface GtalkDataMessageStanza : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int actualDelay; // @dynamic actualDelay;
@property(retain, nonatomic) NSMutableArray *appDataArray; // @dynamic appDataArray;
@property(readonly, nonatomic) unsigned int appDataArray_Count; // @dynamic appDataArray_Count;
@property(copy, nonatomic) NSString *category; // @dynamic category;
@property(retain, nonatomic) GtalkCellTower *cellTower; // @dynamic cellTower;
@property(copy, nonatomic) NSString *clientId; // @dynamic clientId;
@property(nonatomic) BOOL deliveryReceiptRequested; // @dynamic deliveryReceiptRequested;
@property(nonatomic) long long deviceUserId; // @dynamic deviceUserId;
@property(copy, nonatomic) NSString *externalMessageId; // @dynamic externalMessageId;
@property(nonatomic) long long flags; // @dynamic flags;
@property(copy, nonatomic) NSString *from; // @dynamic from;
@property(nonatomic) BOOL fromTrustedServer; // @dynamic fromTrustedServer;
@property(nonatomic) BOOL hasActualDelay; // @dynamic hasActualDelay;
@property(nonatomic) BOOL hasCategory; // @dynamic hasCategory;
@property(nonatomic) BOOL hasCellTower; // @dynamic hasCellTower;
@property(nonatomic) BOOL hasClientId; // @dynamic hasClientId;
@property(nonatomic) BOOL hasDeliveryReceiptRequested; // @dynamic hasDeliveryReceiptRequested;
@property(nonatomic) BOOL hasDeviceUserId; // @dynamic hasDeviceUserId;
@property(nonatomic) BOOL hasExternalMessageId; // @dynamic hasExternalMessageId;
@property(nonatomic) BOOL hasFlags; // @dynamic hasFlags;
@property(nonatomic) BOOL hasFrom; // @dynamic hasFrom;
@property(nonatomic) BOOL hasFromTrustedServer; // @dynamic hasFromTrustedServer;
@property(nonatomic) BOOL hasId_p; // @dynamic hasId_p;
@property(nonatomic) BOOL hasImmediateAck; // @dynamic hasImmediateAck;
@property(nonatomic) BOOL hasLastStreamIdReceived; // @dynamic hasLastStreamIdReceived;
@property(nonatomic) BOOL hasMaxDelay; // @dynamic hasMaxDelay;
@property(nonatomic) BOOL hasPermission; // @dynamic hasPermission;
@property(nonatomic) BOOL hasPersistentId; // @dynamic hasPersistentId;
@property(nonatomic) BOOL hasPkgSignature; // @dynamic hasPkgSignature;
@property(nonatomic) BOOL hasPriority; // @dynamic hasPriority;
@property(nonatomic) BOOL hasQueued; // @dynamic hasQueued;
@property(nonatomic) BOOL hasRawData; // @dynamic hasRawData;
@property(nonatomic) BOOL hasRegId; // @dynamic hasRegId;
@property(nonatomic) BOOL hasRmqId; // @dynamic hasRmqId;
@property(nonatomic) BOOL hasSent; // @dynamic hasSent;
@property(nonatomic) BOOL hasStatus; // @dynamic hasStatus;
@property(nonatomic) BOOL hasStreamId; // @dynamic hasStreamId;
@property(nonatomic) BOOL hasTo; // @dynamic hasTo;
@property(nonatomic) BOOL hasToken; // @dynamic hasToken;
@property(nonatomic) BOOL hasTtl; // @dynamic hasTtl;
@property(copy, nonatomic) NSString *id_p; // @dynamic id_p;
@property(nonatomic) BOOL immediateAck; // @dynamic immediateAck;
@property(nonatomic) int lastStreamIdReceived; // @dynamic lastStreamIdReceived;
@property(nonatomic) int maxDelay; // @dynamic maxDelay;
@property(copy, nonatomic) NSString *permission; // @dynamic permission;
@property(copy, nonatomic) NSString *persistentId; // @dynamic persistentId;
@property(copy, nonatomic) NSString *pkgSignature; // @dynamic pkgSignature;
@property(nonatomic) int priority; // @dynamic priority;
@property(nonatomic) int queued; // @dynamic queued;
@property(copy, nonatomic) NSData *rawData; // @dynamic rawData;
@property(copy, nonatomic) NSString *regId; // @dynamic regId;
@property(nonatomic) long long rmqId; // @dynamic rmqId;
@property(nonatomic) long long sent; // @dynamic sent;
@property(nonatomic) long long status; // @dynamic status;
@property(nonatomic) int streamId; // @dynamic streamId;
@property(copy, nonatomic) NSString *to; // @dynamic to;
@property(copy, nonatomic) NSString *token; // @dynamic token;
@property(nonatomic) int ttl; // @dynamic ttl;

@end

