//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface GtalkClientEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int errorCode; // @dynamic errorCode;
@property(nonatomic) BOOL hasErrorCode; // @dynamic hasErrorCode;
@property(nonatomic) BOOL hasMcsReconnectAction; // @dynamic hasMcsReconnectAction;
@property(nonatomic) BOOL hasNetworkPort; // @dynamic hasNetworkPort;
@property(nonatomic) BOOL hasNetworkType; // @dynamic hasNetworkType;
@property(nonatomic) BOOL hasNumberDiscardedEvents; // @dynamic hasNumberDiscardedEvents;
@property(nonatomic) BOOL hasTimeConnectionEndedMs; // @dynamic hasTimeConnectionEndedMs;
@property(nonatomic) BOOL hasTimeConnectionEstablishedMs; // @dynamic hasTimeConnectionEstablishedMs;
@property(nonatomic) BOOL hasTimeConnectionStartedMs; // @dynamic hasTimeConnectionStartedMs;
@property(nonatomic) BOOL hasType; // @dynamic hasType;
@property(nonatomic) int mcsReconnectAction; // @dynamic mcsReconnectAction;
@property(nonatomic) int networkPort; // @dynamic networkPort;
@property(nonatomic) int networkType; // @dynamic networkType;
@property(nonatomic) unsigned int numberDiscardedEvents; // @dynamic numberDiscardedEvents;
@property(nonatomic) unsigned long long timeConnectionEndedMs; // @dynamic timeConnectionEndedMs;
@property(nonatomic) unsigned long long timeConnectionEstablishedMs; // @dynamic timeConnectionEstablishedMs;
@property(nonatomic) unsigned long long timeConnectionStartedMs; // @dynamic timeConnectionStartedMs;
@property(nonatomic) int type; // @dynamic type;

@end

