//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GtalkRosterQuery : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int avatarHeight; // @dynamic avatarHeight;
@property(nonatomic) int avatarWidth; // @dynamic avatarWidth;
@property(copy, nonatomic) NSString *etag; // @dynamic etag;
@property(nonatomic) BOOL hasAvatarHeight; // @dynamic hasAvatarHeight;
@property(nonatomic) BOOL hasAvatarWidth; // @dynamic hasAvatarWidth;
@property(nonatomic) BOOL hasEtag; // @dynamic hasEtag;
@property(nonatomic) BOOL hasNotModified; // @dynamic hasNotModified;
@property(retain, nonatomic) NSMutableArray *itemArray; // @dynamic itemArray;
@property(readonly, nonatomic) unsigned int itemArray_Count; // @dynamic itemArray_Count;
@property(nonatomic) BOOL notModified; // @dynamic notModified;

@end

