//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GtalkCapabilities : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *ext; // @dynamic ext;
@property(nonatomic) BOOL hasExt; // @dynamic hasExt;
@property(nonatomic) BOOL hasHash_p; // @dynamic hasHash_p;
@property(nonatomic) BOOL hasNode; // @dynamic hasNode;
@property(nonatomic) BOOL hasVer; // @dynamic hasVer;
@property(copy, nonatomic) NSString *hash_p; // @dynamic hash_p;
@property(copy, nonatomic) NSString *node; // @dynamic node;
@property(copy, nonatomic) NSString *ver; // @dynamic ver;

@end

