//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface GtalkSharedStatus_StatusList : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) BOOL hasShow; // @dynamic hasShow;
@property(nonatomic) int show; // @dynamic show;
@property(retain, nonatomic) NSMutableArray *statusArray; // @dynamic statusArray;
@property(readonly, nonatomic) unsigned int statusArray_Count; // @dynamic statusArray_Count;

@end

