//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GtalkPhoto, NSString;

@interface GtalkVCard : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *avatarHash; // @dynamic avatarHash;
@property(copy, nonatomic) NSString *fullName; // @dynamic fullName;
@property(nonatomic) BOOL hasAvatarHash; // @dynamic hasAvatarHash;
@property(nonatomic) BOOL hasFullName; // @dynamic hasFullName;
@property(nonatomic) BOOL hasModified; // @dynamic hasModified;
@property(nonatomic) BOOL hasPhoto; // @dynamic hasPhoto;
@property(nonatomic) BOOL hasVersion; // @dynamic hasVersion;
@property(nonatomic) BOOL modified; // @dynamic modified;
@property(retain, nonatomic) GtalkPhoto *photo; // @dynamic photo;
@property(copy, nonatomic) NSString *version; // @dynamic version;

@end

