//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GtalkPostAuthBatchQuery : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) BOOL available; // @dynamic available;
@property(copy, nonatomic) NSString *avatarHash; // @dynamic avatarHash;
@property(nonatomic) int capabilitiesExtFlags; // @dynamic capabilitiesExtFlags;
@property(nonatomic) BOOL deviceIdle; // @dynamic deviceIdle;
@property(nonatomic) BOOL hasAvailable; // @dynamic hasAvailable;
@property(nonatomic) BOOL hasAvatarHash; // @dynamic hasAvatarHash;
@property(nonatomic) BOOL hasCapabilitiesExtFlags; // @dynamic hasCapabilitiesExtFlags;
@property(nonatomic) BOOL hasDeviceIdle; // @dynamic hasDeviceIdle;
@property(nonatomic) BOOL hasMobileIndicator; // @dynamic hasMobileIndicator;
@property(nonatomic) BOOL hasOtrEtag; // @dynamic hasOtrEtag;
@property(nonatomic) BOOL hasRosterEtag; // @dynamic hasRosterEtag;
@property(nonatomic) BOOL hasSharedStatusVersion; // @dynamic hasSharedStatusVersion;
@property(nonatomic) BOOL hasVcardQueryStanzaId; // @dynamic hasVcardQueryStanzaId;
@property(nonatomic) BOOL mobileIndicator; // @dynamic mobileIndicator;
@property(copy, nonatomic) NSString *otrEtag; // @dynamic otrEtag;
@property(copy, nonatomic) NSString *rosterEtag; // @dynamic rosterEtag;
@property(nonatomic) int sharedStatusVersion; // @dynamic sharedStatusVersion;
@property(copy, nonatomic) NSString *vcardQueryStanzaId; // @dynamic vcardQueryStanzaId;

@end

