//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface Logs : NSObject
{
    NSMutableArray *_buffer;
    double _timeForAutoUpdate;
    double _timeForButtonUpdate;
}

+ (id)logs;
@property(nonatomic) double timeForButtonUpdate; // @synthesize timeForButtonUpdate=_timeForButtonUpdate;
@property(nonatomic) double timeForAutoUpdate; // @synthesize timeForAutoUpdate=_timeForAutoUpdate;
@property(retain, nonatomic) NSMutableArray *buffer; // @synthesize buffer=_buffer;
- (void).cxx_destruct;
- (void)sendJSONArray:(id)arg1 count:(int)arg2;
- (void)createRequest;
- (void)sendLogsButton:(BOOL)arg1;
- (void)saveLogForService:(id)arg1 httpError:(id)arg2 log:(id)arg3;
- (void)save;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

