//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIView;

@interface NavigationHistorySearchCell : UITableViewCell
{
    UILabel *_name;
    UILabel *_address;
    UIView *_iconBackground;
    UILabel *_icon;
}

@property(nonatomic) __weak UILabel *icon; // @synthesize icon=_icon;
@property(nonatomic) __weak UIView *iconBackground; // @synthesize iconBackground=_iconBackground;
@property(nonatomic) __weak UILabel *address; // @synthesize address=_address;
@property(nonatomic) __weak UILabel *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

