//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CLLocationManagerDelegate.h"
#import "UIAlertViewDelegate.h"

@class CLLocationManager, CustomActivityIndicator, LoginPopupViewController, NSArray, NSLayoutConstraint, NSString, UIImageView, UILabel, UIStackView, UIView;

@interface NavigationDashboardViewController : UIViewController <UIAlertViewDelegate, CLLocationManagerDelegate>
{
    LoginPopupViewController *lpvc;
    CustomActivityIndicator *loading;
    float score;
    float distance;
    int trip_count;
    int days_left;
    NSArray *historyMonths;
    int staticScore;
    int staticDistance;
    int staticTripCount;
    NSLayoutConstraint *barConstraint;
    CLLocationManager *manager;
    BOOL isOpeningNavigation;
    UILabel *_safedrivingLabel;
    UILabel *_monthLabel;
    UIView *_barShadow;
    UIView *_barRoundedView;
    UIView *_barArrows;
    UIView *_barProgress;
    UILabel *_barProgressNumber;
    UILabel *_barNumber80;
    UIStackView *_monthlyStatsStackView;
    UILabel *_statsKMLabel;
    UILabel *_statsKM;
    UILabel *_statsRides;
    UILabel *_statsRidesLabel;
    UILabel *_statsDaysLeft;
    UILabel *_statsDaysLeftLabel;
    UILabel *_bonusDataDesc;
    UIView *_barButtonView;
    UIView *_middleButtonView;
    UIImageView *_middleButtonImage;
}

@property(nonatomic) __weak UIImageView *middleButtonImage; // @synthesize middleButtonImage=_middleButtonImage;
@property(nonatomic) __weak UIView *middleButtonView; // @synthesize middleButtonView=_middleButtonView;
@property(nonatomic) __weak UIView *barButtonView; // @synthesize barButtonView=_barButtonView;
@property(nonatomic) __weak UILabel *bonusDataDesc; // @synthesize bonusDataDesc=_bonusDataDesc;
@property(nonatomic) __weak UILabel *statsDaysLeftLabel; // @synthesize statsDaysLeftLabel=_statsDaysLeftLabel;
@property(nonatomic) __weak UILabel *statsDaysLeft; // @synthesize statsDaysLeft=_statsDaysLeft;
@property(nonatomic) __weak UILabel *statsRidesLabel; // @synthesize statsRidesLabel=_statsRidesLabel;
@property(nonatomic) __weak UILabel *statsRides; // @synthesize statsRides=_statsRides;
@property(nonatomic) __weak UILabel *statsKM; // @synthesize statsKM=_statsKM;
@property(nonatomic) __weak UILabel *statsKMLabel; // @synthesize statsKMLabel=_statsKMLabel;
@property(nonatomic) __weak UIStackView *monthlyStatsStackView; // @synthesize monthlyStatsStackView=_monthlyStatsStackView;
@property(nonatomic) __weak UILabel *barNumber80; // @synthesize barNumber80=_barNumber80;
@property(nonatomic) __weak UILabel *barProgressNumber; // @synthesize barProgressNumber=_barProgressNumber;
@property(nonatomic) __weak UIView *barProgress; // @synthesize barProgress=_barProgress;
@property(nonatomic) __weak UIView *barArrows; // @synthesize barArrows=_barArrows;
@property(nonatomic) __weak UIView *barRoundedView; // @synthesize barRoundedView=_barRoundedView;
@property(nonatomic) __weak UIView *barShadow; // @synthesize barShadow=_barShadow;
@property(nonatomic) __weak UILabel *monthLabel; // @synthesize monthLabel=_monthLabel;
@property(nonatomic) __weak UILabel *safedrivingLabel; // @synthesize safedrivingLabel=_safedrivingLabel;
- (void).cxx_destruct;
- (void)hide;
- (void)immediateShowWithTutorial;
- (void)show;
- (void)clickedInfo:(id)arg1;
- (void)clickedOpenTutorial:(id)arg1;
- (void)clickedOpenHistory:(id)arg1;
- (void)clickedOpenNavigation:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)checkForDrivingLogToSend;
- (void)checkForCode;
- (BOOL)getSerializedHistory;
- (void)serializeHistory;
- (void)getUserData;
- (void)setBarButtonView;
- (void)setupStackView;
- (void)setupProgressBar;
- (void)setupLabels;
- (void)refresh;
- (id)findLayer:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (BOOL)checkGeoLocationAllowed;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)showSygicNavigationDashboardWithCode:(id)arg1;
- (void)reloadData:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

