//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface NotificationCell : UITableViewCell
{
    UIImageView *_image;
    UILabel *_date;
    UILabel *_type;
    UILabel *_text;
}

@property(nonatomic) __weak UILabel *text; // @synthesize text=_text;
@property(nonatomic) __weak UILabel *type; // @synthesize type=_type;
@property(nonatomic) __weak UILabel *date; // @synthesize date=_date;
@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

