//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface Notification : NSObject
{
    BOOL _isNew;
    NSString *_Id;
    NSString *_title;
    NSString *_text;
    NSString *_type;
    NSMutableDictionary *_content;
    double _created;
    double _validTo;
}

@property(nonatomic) BOOL isNew; // @synthesize isNew=_isNew;
@property(retain, nonatomic) NSMutableDictionary *content; // @synthesize content=_content;
@property(nonatomic) double validTo; // @synthesize validTo=_validTo;
@property(nonatomic) double created; // @synthesize created=_created;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *Id; // @synthesize Id=_Id;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

