//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel, UIView;

@interface OffersCell : UICollectionViewCell
{
    UIView *_bgView;
    UIImageView *_image;
    UIImageView *_imagePartner;
    UILabel *_text;
    UILabel *_discount;
    UIView *_discountView;
}

@property(nonatomic) __weak UIView *discountView; // @synthesize discountView=_discountView;
@property(nonatomic) __weak UILabel *discount; // @synthesize discount=_discount;
@property(nonatomic) __weak UILabel *text; // @synthesize text=_text;
@property(nonatomic) __weak UIImageView *imagePartner; // @synthesize imagePartner=_imagePartner;
@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

