//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface Offer : NSObject
{
    BOOL _show;
    BOOL _geoPushAllow;
    BOOL _isNew;
    BOOL _hasChildren;
    BOOL _checkAvailability;
    BOOL _claimed;
    NSString *_Id;
    NSString *_name;
    NSString *_discount;
    NSString *_imageSmall;
    NSString *_imageBig;
    NSString *_imagePartner;
    NSString *_smsNumber;
    NSString *_smsText;
    NSString *_buttonText;
    NSString *_codeDetailText;
    NSString *_geoPushText;
    NSMutableArray *_descriptions;
    NSMutableArray *_categories;
    NSMutableArray *_related;
    NSMutableDictionary *_gps;
    NSString *_parent;
    int _codeShowMethod;
    NSString *_type;
    NSString *_url;
    double _validFrom;
    double _validTo;
}

@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(nonatomic) BOOL claimed; // @synthesize claimed=_claimed;
@property(nonatomic) int codeShowMethod; // @synthesize codeShowMethod=_codeShowMethod;
@property(nonatomic) BOOL checkAvailability; // @synthesize checkAvailability=_checkAvailability;
@property(nonatomic) BOOL hasChildren; // @synthesize hasChildren=_hasChildren;
@property(retain, nonatomic) NSString *parent; // @synthesize parent=_parent;
@property(nonatomic) BOOL isNew; // @synthesize isNew=_isNew;
@property(retain, nonatomic) NSMutableDictionary *gps; // @synthesize gps=_gps;
@property(retain, nonatomic) NSMutableArray *related; // @synthesize related=_related;
@property(retain, nonatomic) NSMutableArray *categories; // @synthesize categories=_categories;
@property(retain, nonatomic) NSMutableArray *descriptions; // @synthesize descriptions=_descriptions;
@property(retain, nonatomic) NSString *geoPushText; // @synthesize geoPushText=_geoPushText;
@property(nonatomic) BOOL geoPushAllow; // @synthesize geoPushAllow=_geoPushAllow;
@property(retain, nonatomic) NSString *codeDetailText; // @synthesize codeDetailText=_codeDetailText;
@property(retain, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(retain, nonatomic) NSString *smsText; // @synthesize smsText=_smsText;
@property(retain, nonatomic) NSString *smsNumber; // @synthesize smsNumber=_smsNumber;
@property(nonatomic) BOOL show; // @synthesize show=_show;
@property(nonatomic) double validTo; // @synthesize validTo=_validTo;
@property(nonatomic) double validFrom; // @synthesize validFrom=_validFrom;
@property(retain, nonatomic) NSString *imagePartner; // @synthesize imagePartner=_imagePartner;
@property(retain, nonatomic) NSString *imageBig; // @synthesize imageBig=_imageBig;
@property(retain, nonatomic) NSString *imageSmall; // @synthesize imageSmall=_imageSmall;
@property(retain, nonatomic) NSString *discount; // @synthesize discount=_discount;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *Id; // @synthesize Id=_Id;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

