//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface Offers : NSObject
{
    NSMutableDictionary *_list;
    NSMutableArray *_order;
    double _lastUpdate;
}

+ (id)offers;
@property(retain, nonatomic) NSMutableArray *order; // @synthesize order=_order;
@property(retain, nonatomic) NSMutableDictionary *list; // @synthesize list=_list;
@property(nonatomic) double lastUpdate; // @synthesize lastUpdate=_lastUpdate;
- (void).cxx_destruct;
- (id)webviewOffer;
- (void)setClaimedForArray:(id)arg1;
- (id)childsForOffer:(id)arg1;
- (int)countOfNewOffers;
- (void)setNotNewForOffers;
- (id)sortedOffers;
- (void)updateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)save;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

