//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface OfferDetailFooterCell : UITableViewCell
{
    UIView *_view1;
    UIImageView *_image;
    UIImageView *_imagePartner;
    UILabel *_text;
    UILabel *_discount;
    UIView *_discountView1;
    UIButton *_button;
    UIView *_view2;
    UIImageView *_image2;
    UIImageView *_imagePartner2;
    UILabel *_text2;
    UILabel *_discount2;
    UIView *_discountView2;
    UIButton *_button2;
}

@property(nonatomic) __weak UIButton *button2; // @synthesize button2=_button2;
@property(nonatomic) __weak UIView *discountView2; // @synthesize discountView2=_discountView2;
@property(nonatomic) __weak UILabel *discount2; // @synthesize discount2=_discount2;
@property(nonatomic) __weak UILabel *text2; // @synthesize text2=_text2;
@property(nonatomic) __weak UIImageView *imagePartner2; // @synthesize imagePartner2=_imagePartner2;
@property(nonatomic) __weak UIImageView *image2; // @synthesize image2=_image2;
@property(nonatomic) __weak UIView *view2; // @synthesize view2=_view2;
@property(nonatomic) __weak UIButton *button; // @synthesize button=_button;
@property(nonatomic) __weak UIView *discountView1; // @synthesize discountView1=_discountView1;
@property(nonatomic) __weak UILabel *discount; // @synthesize discount=_discount;
@property(nonatomic) __weak UILabel *text; // @synthesize text=_text;
@property(nonatomic) __weak UIImageView *imagePartner; // @synthesize imagePartner=_imagePartner;
@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
@property(nonatomic) __weak UIView *view1; // @synthesize view1=_view1;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

