//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class CampaignHTMLViewController, CustomActivityIndicator, LoginPopupViewController, NSMutableArray, NSString, NoBirthdayViewController, UIButton, UICollectionView, UILabel;

@interface OffersViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    NSMutableArray *tableData;
    OffersViewController *ovc;
    LoginPopupViewController *lpvc;
    NoBirthdayViewController *nbvc;
    CampaignHTMLViewController *hvc;
    CustomActivityIndicator *loading;
    int clickedIndex;
    BOOL visible;
    int _type;
    NSString *_headerText;
    NSMutableArray *_offers;
    UILabel *_navigationTitle;
    UICollectionView *_table;
    UIButton *_buttonBack;
}

@property(nonatomic) __weak UIButton *buttonBack; // @synthesize buttonBack=_buttonBack;
@property(nonatomic) __weak UICollectionView *table; // @synthesize table=_table;
@property(nonatomic) __weak UILabel *navigationTitle; // @synthesize navigationTitle=_navigationTitle;
@property(retain, nonatomic) NSMutableArray *offers; // @synthesize offers=_offers;
@property(retain, nonatomic) NSString *headerText; // @synthesize headerText=_headerText;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)anniversaryAfterLogout;
- (void)clickedBack:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)showOffer:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)refresh;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

