//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class LoginViewController, UIButton, UINavigationController;

@interface OnboardViewController : UIViewController
{
    UINavigationController *nc;
    LoginViewController *lvc;
    UIButton *_buttonLogin;
}

@property(nonatomic) __weak UIButton *buttonLogin; // @synthesize buttonLogin=_buttonLogin;
- (void).cxx_destruct;
- (void)clickedClose:(id)arg1;
- (void)clickedLogin:(id)arg1;
- (void)logged;
- (void)show;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

