//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class LoginPopupViewController, LoginViewController, UIButton, UILabel, UIScrollView, UIView;

@interface ProfileViewController : UIViewController
{
    LoginViewController *lvc;
    LoginPopupViewController *lpvc;
    UIScrollView *_scroll;
    UIView *_topView;
    UIView *_midView;
    UIView *_bg;
    UILabel *_phoneNumber;
    UIButton *_buttonLogin;
}

@property(nonatomic) __weak UIButton *buttonLogin; // @synthesize buttonLogin=_buttonLogin;
@property(nonatomic) __weak UILabel *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(nonatomic) __weak UIView *bg; // @synthesize bg=_bg;
@property(nonatomic) __weak UIView *midView; // @synthesize midView=_midView;
@property(nonatomic) __weak UIView *topView; // @synthesize topView=_topView;
@property(nonatomic) __weak UIScrollView *scroll; // @synthesize scroll=_scroll;
- (void).cxx_destruct;
- (void)openForm;
- (void)clickedAbout:(id)arg1;
- (void)clickedMojeO2:(id)arg1;
- (void)clickedSettings:(id)arg1;
- (void)clickedMyProfile:(id)arg1;
- (void)clickedLogin:(id)arg1;
- (void)refresh;
- (void)viewDidLoad;

@end

