//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface Question : NSObject
{
    BOOL _active;
    NSString *_Id;
    NSString *_text;
    NSString *_type;
    NSMutableDictionary *_answers;
}

@property(retain, nonatomic) NSMutableDictionary *answers; // @synthesize answers=_answers;
@property(nonatomic) BOOL active; // @synthesize active=_active;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *Id; // @synthesize Id=_Id;
- (void).cxx_destruct;
- (id)sortedAnswers;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

