//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIView;

@interface ShadowCell : UITableViewCell
{
    UIView *_bg;
}

@property(nonatomic) __weak UIView *bg; // @synthesize bg=_bg;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

