//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SYDriving, SYDrivingDistracting, SYDrivingFastCornering, SYDrivingHardAccelerating, SYDrivingHardBraking, SYDrivingSpeeding;

@protocol SYDrivingDelegate <NSObject>

@optional
- (void)driving:(SYDriving *)arg1 didDetectDistracting:(SYDrivingDistracting *)arg2;
- (void)driving:(SYDriving *)arg1 didDetectHardAccelerating:(SYDrivingHardAccelerating *)arg2;
- (void)driving:(SYDriving *)arg1 didDetectHardBraking:(SYDrivingHardBraking *)arg2;
- (void)driving:(SYDriving *)arg1 didDetectSpeeding:(SYDrivingSpeeding *)arg2;
- (void)driving:(SYDriving *)arg1 didDetectFastCornering:(SYDrivingFastCornering *)arg2;
@end

