//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CustomActivityIndicator, NSLayoutConstraint, UIButton, UIImageView, UILabel, UIPageControl, UIScrollView, UITextView, UIView;

@interface SygicTutorialViewController : UIViewController
{
    CustomActivityIndicator *loading;
    BOOL _showingAsPopup;
    BOOL _showingWithoutImage;
    UILabel *_Title;
    int _screenNumber;
    UIImageView *_imageView;
    UIView *_progressBarView;
    UIPageControl *_pageControl;
    UIView *_arrowCircle;
    UITextView *_tutorialLabel;
    UIView *_nextView;
    UIButton *_next;
    UIView *_finishView;
    UIButton *_finish;
    UIScrollView *_scrollView;
    UIImageView *_imageBackground;
    UIButton *_popupButton;
    UIView *_transparentBackground;
    NSLayoutConstraint *_bottomCons;
    UIView *_constraintView;
    NSLayoutConstraint *_topCons;
}

@property(nonatomic) __weak NSLayoutConstraint *topCons; // @synthesize topCons=_topCons;
@property(nonatomic) __weak UIView *constraintView; // @synthesize constraintView=_constraintView;
@property(nonatomic) __weak NSLayoutConstraint *bottomCons; // @synthesize bottomCons=_bottomCons;
@property(nonatomic) __weak UIView *transparentBackground; // @synthesize transparentBackground=_transparentBackground;
@property(nonatomic) __weak UIButton *popupButton; // @synthesize popupButton=_popupButton;
@property(nonatomic) __weak UIImageView *imageBackground; // @synthesize imageBackground=_imageBackground;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIButton *finish; // @synthesize finish=_finish;
@property(nonatomic) __weak UIView *finishView; // @synthesize finishView=_finishView;
@property(nonatomic) __weak UIButton *next; // @synthesize next=_next;
@property(nonatomic) __weak UIView *nextView; // @synthesize nextView=_nextView;
@property(nonatomic) __weak UITextView *tutorialLabel; // @synthesize tutorialLabel=_tutorialLabel;
@property(nonatomic) __weak UIView *arrowCircle; // @synthesize arrowCircle=_arrowCircle;
@property(nonatomic) __weak UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) __weak UIView *progressBarView; // @synthesize progressBarView=_progressBarView;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) int screenNumber; // @synthesize screenNumber=_screenNumber;
@property(nonatomic) __weak UILabel *Title; // @synthesize Title=_Title;
@property BOOL showingWithoutImage; // @synthesize showingWithoutImage=_showingWithoutImage;
@property BOOL showingAsPopup; // @synthesize showingAsPopup=_showingAsPopup;
- (void).cxx_destruct;
- (void)hide:(BOOL)arg1 orderNumber:(id)arg2;
- (void)showAsPopupWithoutImage:(double)arg1;
- (void)showAsPopup:(double)arg1;
- (void)show:(double)arg1;
- (void)changePageControl:(id)arg1;
- (void)clickedFinish:(id)arg1;
- (void)clickedNext:(id)arg1;
- (void)setupLabels;
- (void)setupButtons;
- (void)setupViews;
- (void)viewDidLoad;

@end

