//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UIScrollView, UITextView;

@interface SygicTutorialView : UIView
{
    UIImageView *_image;
    UITextView *_tutorialLabel;
    UIScrollView *_scrollView;
}

@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UITextView *tutorialLabel; // @synthesize tutorialLabel=_tutorialLabel;
@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
- (void).cxx_destruct;

@end

