//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CustomActivityIndicator, UIButton, UILabel, UIView;

@interface SygicAgreementViewController : UIViewController
{
    BOOL marketing;
    CustomActivityIndicator *loading;
    UIView *_blurView;
    UIView *_contentView;
    UILabel *_header;
    UILabel *_subheader;
    UIView *_marketingView;
    UILabel *_textMarketing;
    UIButton *_buttonMarketing;
    UIButton *_buttonOk;
    UIButton *_buttonClose;
}

@property(nonatomic) __weak UIButton *buttonClose; // @synthesize buttonClose=_buttonClose;
@property(nonatomic) __weak UIButton *buttonOk; // @synthesize buttonOk=_buttonOk;
@property(nonatomic) __weak UIButton *buttonMarketing; // @synthesize buttonMarketing=_buttonMarketing;
@property(nonatomic) __weak UILabel *textMarketing; // @synthesize textMarketing=_textMarketing;
@property(nonatomic) __weak UIView *marketingView; // @synthesize marketingView=_marketingView;
@property(nonatomic) __weak UILabel *subheader; // @synthesize subheader=_subheader;
@property(nonatomic) __weak UILabel *header; // @synthesize header=_header;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *blurView; // @synthesize blurView=_blurView;
- (void).cxx_destruct;
- (void)setAgreements;
- (void)tappedMarketing:(id)arg1;
- (void)clickedMarketing;
- (void)setButtons;
- (void)clickedClose:(id)arg1;
- (void)clickedBack:(id)arg1;
- (void)showWithImage:(id)arg1;
- (void)viewDidLoad;

@end

