//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class AgreementsViewController, CampaignViewController, LoginViewController, OnboardViewController, SygicAgreementViewController, UIImageView, UILabel, UINavigationController, UIView;

@interface TabBarViewController : UIViewController
{
    int index;
    BOOL openingNavDashboard;
    UINavigationController *tab1nc;
    UINavigationController *tab2nc;
    UINavigationController *tab3nc;
    UINavigationController *tab4nc;
    LoginViewController *lvc;
    OnboardViewController *ovc;
    CampaignViewController *cvc;
    AgreementsViewController *avc;
    SygicAgreementViewController *savc;
    UIView *_resizeView;
    UIView *_content;
    UIImageView *_bar1;
    UIImageView *_bar2;
    UIImageView *_bar3;
    UIImageView *_bar4;
    UILabel *_bar1Name;
    UILabel *_bar2Name;
    UILabel *_bar3Name;
    UILabel *_bar4Name;
    UILabel *_bar1Counter;
    UILabel *_bar3Counter;
    UIView *_bannerView;
    UILabel *_bannerText;
}

@property(nonatomic) __weak UILabel *bannerText; // @synthesize bannerText=_bannerText;
@property(nonatomic) __weak UIView *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) __weak UILabel *bar3Counter; // @synthesize bar3Counter=_bar3Counter;
@property(nonatomic) __weak UILabel *bar1Counter; // @synthesize bar1Counter=_bar1Counter;
@property(nonatomic) __weak UILabel *bar4Name; // @synthesize bar4Name=_bar4Name;
@property(nonatomic) __weak UILabel *bar3Name; // @synthesize bar3Name=_bar3Name;
@property(nonatomic) __weak UILabel *bar2Name; // @synthesize bar2Name=_bar2Name;
@property(nonatomic) __weak UILabel *bar1Name; // @synthesize bar1Name=_bar1Name;
@property(nonatomic) __weak UIImageView *bar4; // @synthesize bar4=_bar4;
@property(nonatomic) __weak UIImageView *bar3; // @synthesize bar3=_bar3;
@property(nonatomic) __weak UIImageView *bar2; // @synthesize bar2=_bar2;
@property(nonatomic) __weak UIImageView *bar1; // @synthesize bar1=_bar1;
@property(nonatomic) __weak UIView *content; // @synthesize content=_content;
@property(nonatomic) __weak UIView *resizeView; // @synthesize resizeView=_resizeView;
- (void).cxx_destruct;
- (int)preferredStatusBarStyle;
- (BOOL)prefersStatusBarHidden;
- (void)resizeViewWithTop;
- (void)resizeViewWithoutTop;
- (void)showSygicNavigationDashboard:(id)arg1;
- (void)showSygicAgreement;
- (void)showAgreement;
- (void)refreshBanner;
- (void)refresh;
- (void)loggedInRefresh;
- (void)notificationReceivedBeforeStart:(id)arg1;
- (void)notificationReceived:(id)arg1;
- (void)openOffer:(id)arg1;
- (void)clickedBanner:(id)arg1;
- (void)showLogin;
- (void)barNavigationClicked:(id)arg1;
- (void)bar4Clicked:(id)arg1;
- (void)bar3Clicked:(id)arg1;
- (void)bar2Clicked:(id)arg1;
- (void)bar1Clicked:(id)arg1;
- (void)remakeBars;
- (void)onboardClose;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

