//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface User : NSObject
{
    BOOL _geoPushEnabled;
    NSString *_accessToken;
    NSString *_deviceToken;
    NSString *_appToken;
    NSString *_phoneNumber;
    NSString *_agreementApp;
    NSString *_agreementMkt;
    NSString *_agreementNav;
    NSMutableDictionary *_form;
}

+ (id)user;
@property(retain, nonatomic) NSMutableDictionary *form; // @synthesize form=_form;
@property(retain, nonatomic) NSString *agreementNav; // @synthesize agreementNav=_agreementNav;
@property(retain, nonatomic) NSString *agreementMkt; // @synthesize agreementMkt=_agreementMkt;
@property(retain, nonatomic) NSString *agreementApp; // @synthesize agreementApp=_agreementApp;
@property(nonatomic) BOOL geoPushEnabled; // @synthesize geoPushEnabled=_geoPushEnabled;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) NSString *appToken; // @synthesize appToken=_appToken;
@property(retain, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(retain, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (void).cxx_destruct;
- (BOOL)haveFilledForm;
- (id)sortedActiveForm;
- (id)sortedForm;
- (void)agreementWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)o2logout;
- (void)logoutWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)loginWithCode:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)save;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

