//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Utils : NSObject
{
}

+ (BOOL)didTapAttributedTextInLabel:(id)arg1 inRange:(struct _NSRange)arg2 tapGesture:(id)arg3;
+ (int)getDaysLeft;
+ (int)getActualYearNumber;
+ (int)getActualMonthNumber;
+ (BOOL)isBothDatesToday:(id)arg1 date2:(id)arg2;
+ (id)returnMonthFromNumber:(int)arg1;
+ (id)getActualMonth;
+ (id)stringFromDate:(double)arg1;
+ (id)customLightFont:(float)arg1;
+ (id)customBoldFont:(float)arg1;
+ (id)customFont:(float)arg1;
+ (BOOL)validEmail:(id)arg1;
+ (BOOL)pushNotificationsAreEnabled;
+ (id)encodeToHTML:(id)arg1;
+ (BOOL)connected;
+ (id)getUUID;

@end

